### ISSUE TITLE
CDC dmlManager panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10081]
### What did you do?

1. Run CDC changefeed with redo log on
2. Run workloads

### What did you expect to see?

CDC not panic

### What did you see instead?

CDC panic seen

```
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079399359+08:00 stderr F \tgolang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x96","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079397393+08:00 stderr F created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1783","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079395478+08:00 stderr F \tgolang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x56","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079393599+08:00 stderr F golang.org/x/sync/errgroup.(*Group).Go.func1()","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079391285+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:418 +0x2a","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079389485+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startRedoWorkers.func1()","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079387598+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/redo_log_worker.go:64 +0xbd","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079385722+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*redoWorker).handleTasks(0x0?, {0x4292390, 0xc002c19180}, 0xc002799b60)","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079382488+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/redo_log_worker.go:295 +0xcfb","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079375465+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*redoWorker).handleTask(0xc002c19270, {0x4292390, 0xc002c19180}, 0xc01358e8c0)","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079372544+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/redo_log_worker.go:170 +0x3f5","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079370645+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*redoWorker).handleTask.func2(0x0, 0x0)","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079368321+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/redo_log_worker.go:129 +0x13a","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079366078+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*redoWorker).handleTask.func1()","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079363713+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/redo/manager.go:140 +0xa","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079360094+08:00 stderr F github.com/pingcap/tiflow/cdc/redo.(*dmlManager).EmitRowChangedEvents(0x153e?, {0x1543?, 0x464692?}, 0xc003367600?, 0xc003367648?, {0x1543?, 0x1543?, 0xc?})","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079356321+08:00 stderr F goroutine 1797 [running]:","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079354042+08:00 stderr F ","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079348209+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d2d5aa]","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
2023-11-08 15:08:31	
{"log":"2023-11-08T15:08:31.079318392+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference","container":"ticdc","namespace":"xxx-cdc-tps-3630374-1-582","pod":"tc-ticdc-0"}
```

### Versions of the cluster

[release-version=v6.5.0-master-dirty] [git-hash=624f679b6faa03e1d333d479dbfe88ddc141858f]

**Comment by sdojjy** [comment]
runtime error: invalid memory address or nil pointer dereference

**Comment by sdojjy** [comment]
![image](https://github.com/pingcap/tiflow/assets/1779704/6fcb4cf4-d4d0-4d4b-b805-d8284e8dd3f9)

![image](https://github.com/pingcap/tiflow/assets/1779704/ca4a2884-491d-415a-904b-847299f88498)

**Comment by asddongmen** [comment]
Close it since it's never happen again.
