### ISSUE TITLE
CDC EventSorter panic: send on closed channel

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10082]
### What did you do?

1. Run cdc changefeed and workload

### What did you expect to see?

no panic

### What did you see instead?

```
2023-11-07 11:02:13	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"[tz.go:34] [\"Use the timezone of the TiCDC server machine\"] [timezoneName=System] [timezone=Asia/Shanghai]","level":"INFO"}
2023-11-07 11:02:13	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"[helper.go:50] [\"init log\"] [file=/var/lib/ticdc/log/ticdc.log] [level=info]","level":"INFO"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741837555+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:125 +0x4f3"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741835724+08:00 stderr F created by github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start in goroutine 899"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741833317+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/puller/puller_wrapper.go:136 +0x27a"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.74182947+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sourcemanager/puller.(*Wrapper).Start.func3()"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741827469+08:00 stderr F \tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:173 +0x370"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741824298+08:00 stderr F github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).Add(0xc009ff2b00, 0x217a, {0xc0ce46c920, 0x1, 0x1?})"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741821727+08:00 stderr F goroutine 59152 [running]:"}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.74181833+08:00 stderr F "}
2023-11-07 11:02:10	
{"container":"ticdc","namespace":"hzbank-cdc-tps-3630374-1-582","pod":"tc-ticdc-0","log":"2023-11-07T11:02:10.741785579+08:00 stderr F panic: send on closed channel"}
```
![image](https://github.com/pingcap/tiflow/assets/7403864/076c8241-09d9-4efa-9f24-300f841b2fcc)

### Versions of the cluster

[release-version=v6.5.5-20231103-1b62946-1-gb4e5e35f7] [git-hash=b4e5e35f74a0bd59f20b5700aece54f59c329b86]

**Comment by sdojjy** [comment]
cdc is closing
![image](https://github.com/pingcap/tiflow/assets/1779704/2b092817-878f-4fa6-bca8-059317434dfc)

**Comment by sdojjy** [comment]
table actor is not used anymore,  close
