### ISSUE TITLE
cdc server panic since nil pointer found when the changefeed `handleBarrier`

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#10173]
### What did you do?

run the integration test, nothing special

### What did you expect to see?

nothing

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a44bee]

goroutine 97 [running]:
github.com/pingcap/tiflow/cdc/owner.(*changefeed).handleBarrier(0xc0027a7180, {0xc2a3010?, 0xc002c140d8}, 0xc002b5a340, 0xc0016dc390, 0x0)
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/cdc/owner/changefeed.go:884 +0x90e
github.com/pingcap/tiflow/cdc/owner.(*changefeed).tick(0xc0027a7180, {0xc2a3010?, 0xc002c140d8}, 0x10001fbb667d038?)
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/cdc/owner/changefeed.go:394 +0x7d9
github.com/pingcap/tiflow/cdc/owner.(*changefeed).Tick(0xc0027a7180, {0xc2a3060, 0xc002c14090}, 0xc002b5a340, 0xc0016dc390, 0xa3680f8?)
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/cdc/owner/changefeed.go:275 +0x60c
github.com/pingcap/tiflow/cdc/owner.(*ownerImpl).Tick(0xc002e33300, {0x7efc23687f78?, 0xc001012d00}, {0xc272cc0?, 0xc0014684d0})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/cdc/owner/owner.go:207 +0xc9e
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc003004580, {0x7efc23687f78, 0xc001012d00}, 0xc0031876e0, 0x2faf080, {0xa31ee43, 0x5})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/pkg/orchestrator/etcd_worker.go:290 +0x1d13
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc002e9a7e0, {0xc2a2ed0?, 0xc001012d00}, {0x7efc23483fb0, 0xc002e33300}, {0xc272cc0, 0xc0014684d0}, 0x0?, {0xa31ee43, 0x5})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/cdc/capture/capture.go:584 +0x329
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner.func3()
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_kafka_test/tiflow/cdc/capture/capture.go:520 +0x631
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x77
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 94
	/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x125

```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment]
close this, it's won't affect other users
