### ISSUE TITLE
ticdc: mysql sink merge config may occour panic

### ISSUE THREAD

**Issue by wk989898** [pingcap/tiflow#11558]
### What did you do?

1. Create a `replicaConfig` and set `replicaConfig.Sink = nil`
2. creates a new SinkFactory with `replicaConfig`

### What did you expect to see?

create SinkFactory successfully

### What did you see instead?

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x629c971]

goroutine 1 [running]:
github.com/pingcap/tiflow/pkg/sink/mysql.mergeConfig(0xc002239290, 0x6aabaa0?)
	github.com/pingcap/tiflow/pkg/sink/mysql/config.go:228 +0x31
github.com/pingcap/tiflow/pkg/sink/mysql.(*Config).Apply(0xc0012c19a0, {0x762baae, 0x6}, {{0x7630e56?, 0x2?}, {0x765166c?, 0x0?}}, 0xc002239830, 0xc002239290)
	github.com/pingcap/tiflow/pkg/sink/mysql/config.go:167 +0x186
github.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql.NewMySQLBackends({0x828bea0, 0xc0012a9220}, {{0x7630e56?, 0x2656bc9?}, {0x765166c?, 0x7fff16cbc2f2?}}, 0x1?, 0x1?, {0x82602e8, 0xbf0dac0}, ...)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/txn/mysql/mysql.go:96 +0x235
github.com/pingcap/tiflow/cdc/sink/dmlsink/txn.NewMySQLSink({0x828bea0?, 0xc0012a90e0?}, {{0x7630e56?, 0x10?}, {0x765166c?, 0xc0022244e0?}}, 0xc002239830, 0x7f1a93f385b8?, 0x10?, 0x4000)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/txn/txn_dml_sink.go:77 +0x10f
github.com/pingcap/tiflow/cdc/sink/dmlsink/factory.New({0x828bea0, 0xc0012a90e0}, {{0x7630e56?, 0xd415840?}, {0x765166c?, 0x23442dc?}}, {0x7fff16cbc2d7?, 0xc001fbf2f0?}, 0xc002239290, 0xc0022244e0, ...)
	github.com/pingcap/tiflow/cdc/sink/dmlsink/factory/factory.go:85 +0x425
```

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by flowbehappy** [comment]
Will further investigate the issue on the new arch ticdc https://github.com/pingcap/ticdc. Won't fix on the current repo.
