### ISSUE TITLE
DM panic error

### ISSUE THREAD

**Issue by verbotenj** [pingcap/tiflow#11871]
### What did you do?

DM task has been working and stopped.

### What did you expect to see?

Task to continue running.

### What did you see instead?

```panic: runtime error: index out of range [8] with length 8

goroutine 89 [running]:
github.com/pingcap/tiflow/pkg/sqlmodel.getColsAndValuesOfIdx(...)
	github.com/pingcap/tiflow/pkg/sqlmodel/utils.go:32
github.com/pingcap/tiflow/pkg/sqlmodel.(*RowChange).getCausalityString(0x400392fc80, {0x400392fc00?, 0x8, 0x8})
	github.com/pingcap/tiflow/pkg/sqlmodel/causality.go:171 +0x800
github.com/pingcap/tiflow/pkg/sqlmodel.(*RowChange).CausalityKeys(0x400392fc80)
	github.com/pingcap/tiflow/pkg/sqlmodel/causality.go:40 +0x160
github.com/pingcap/tiflow/dm/syncer.(*causality).run(0x40012b0ea0)
	github.com/pingcap/tiflow/dm/syncer/causality.go:83 +0x224
github.com/pingcap/tiflow/dm/syncer.causalityWrap.func1()
	github.com/pingcap/tiflow/dm/syncer/causality.go:60 +0x24
created by github.com/pingcap/tiflow/dm/syncer.causalityWrap in goroutine 572
	github.com/pingcap/tiflow/dm/syncer/causality.go:59 +0x324
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
8.1.1
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
The message you provided "goroutine 89 [running]: ..." is not a panic stack. Please provide the full log / stderr, or some reproducing steps.
