### ISSUE TITLE
http_api flaking test

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#2958]
### Which jobs are flaking?

kafka integration test: http_api

### Which test(s) are flaking?

[2021-09-28T15:18:29.092Z] Traceback (most recent call last):

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 315, in <module>

[2021-09-28T15:18:29.092Z]     func(*sys.argv[2:])

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 92, in pause_changefeed

[2021-09-28T15:18:29.092Z]     assert resp.status_code == rq.codes.accepted

[2021-09-28T15:18:29.092Z] AssertionError

### Jenkins logs or GitHub Actions link

```log
[2021-09-28T15:18:25.029Z] *** etcd info ***:

[2021-09-28T15:18:25.029Z] 

[2021-09-28T15:18:25.029Z] /tidb/cdc/capture/2d6267f7-a019-4d58-995b-262a9e89d335

[2021-09-28T15:18:25.029Z] 	{"id":"2d6267f7-a019-4d58-995b-262a9e89d335","address":"127.0.0.1:8300","version":"v5.3.0-alpha-57-gc9fbc70b"}

[2021-09-28T15:18:25.029Z] 

[2021-09-28T15:18:25.029Z] /tidb/cdc/owner/22317c2cfbecc570

[2021-09-28T15:18:25.029Z] 	2d6267f7-a019-4d58-995b-262a9e89d335'

[2021-09-28T15:18:25.029Z] + grep -q 'etcd info'

[2021-09-28T15:18:25.029Z] + break

[2021-09-28T15:18:25.029Z] + set +x

[2021-09-28T15:18:26.938Z] pass test: check health

[2021-09-28T15:18:26.938Z] pass test: get status

[2021-09-28T15:18:27.196Z] pass test: create changefeed

[2021-09-28T15:18:28.574Z] pass test: list changefeed

[2021-09-28T15:18:28.833Z] pass test: get changefeed

[2021-09-28T15:18:29.092Z] Traceback (most recent call last):

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 315, in <module>

[2021-09-28T15:18:29.092Z]     func(*sys.argv[2:])

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 92, in pause_changefeed

[2021-09-28T15:18:29.092Z]     assert resp.status_code == rq.codes.accepted

[2021-09-28T15:18:29.092Z] AssertionError

[2021-09-28T15:18:51.030Z] make: *** [integration_test_kafka] Error 1
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by hi-rustin** [comment]
/assign @asddongmen 
 
 💚 💙 💜 💛 ❤️

**Comment by hi-rustin** [comment]
/reopen

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/7102/pipeline

```log
[2021-12-07T14:41:48.263Z] + set +x

[2021-12-07T14:41:50.181Z] pass test: check health

[2021-12-07T14:41:50.181Z] pass test: get status

[2021-12-07T14:41:52.728Z] pass test: create changefeed

[2021-12-07T14:41:57.978Z] table test.simple1 not exists for 1-th check, retry later

[2021-12-07T14:41:59.898Z] table test.simple1 not exists for 2-th check, retry later

[2021-12-07T14:42:01.798Z] table test.simple1 not exists for 3-th check, retry later

[2021-12-07T14:42:03.700Z] table test.simple1 not exists for 4-th check, retry later

[2021-12-07T14:42:06.239Z] table test.simple1 not exists for 5-th check, retry later

[2021-12-07T14:42:08.138Z] table test.simple1 not exists for 6-th check, retry later

[2021-12-07T14:42:10.030Z] table test.simple1 not exists for 7-th check, retry later

[2021-12-07T14:42:11.929Z] table test.simple1 not exists for 8-th check, retry later

[2021-12-07T14:42:13.821Z] table test.simple1 not exists for 9-th check, retry later

```

**Comment by asddongmen** [comment]
[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-533)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-534)[2022-04-15T14:09:53.285Z] + [[ ! null =~ null ]]

[2022-04-15T14:09:53.285Z] run task successfully

[2022-04-15T14:09:54.277Z] ('request url', u'https://127.0.0.1:8300/api/v1/processors/changefeed-test2/c9a267ab-a63c-4ff9-a389-7d10152b2fb9[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-535)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-536)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-537)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-538)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-539)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-540)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-541)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-542)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline#step-1136-log-543)')

[2022-04-15T14:09:54.277Z] ('response status code:', 400)

[2022-04-15T14:09:54.277Z] Traceback (most recent call last):

[2022-04-15T14:09:54.277Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/http_api/util/test_case.py", line 334, in <module>

[2022-04-15T14:09:54.277Z]     func(*sys.argv[3:])

[2022-04-15T14:09:54.277Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/http_api/util/test_case.py", line 256, in get_processor

[2022-04-15T14:09:54.277Z]     print("response body:", resp.text())

[2022-04-15T14:09:54.277Z] TypeError: 'unicode' object is not callable

[2022-04-15T14:10:16.164Z] make: *** [integration_test_mysql] Error 1

script returned exit code 2

**Comment by asddongmen** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11268/pipeline

**Comment by hi-rustin** [comment]
another case: https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/11321/pipeline
