### ISSUE TITLE
FAIL	github.com/pingcap/ticdc/cdc/kv	600.625s

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#3302]
### Which jobs are flaking?

unit-test

### Which test(s) are flaking?

FAIL	github.com/pingcap/ticdc/cdc/kv	600.625s

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_test/detail/cdc_ghpr_test/10829/pipeline/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by maxshuang** [comment]
A common solution has been pr in #3612. If you find this issue happens again after this pr, pls reopen the this issue and @ me.

**Comment by hi-rustin** [comment]
happen again:
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/13363/pipeline

```log
[2021-12-01T13:51:49.198Z] [2021/12/01 21:43:41.139 +08:00] [ERROR] [client_test.go:2959] ["mock server error"] [error="rpc error: code = Canceled desc = context canceled"] [stack="github.com/pingcap/ticdc/cdc/kv.(*clientSuite).testKVClientForceReconnect.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_test.go:2959\ngithub.com/pingcap/ticdc/cdc/kv.(*mockChangeDataService).EventFeed.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_test.go:254"]

[2021-12-01T13:51:49.198Z] panic: test timed out after 10m0s

[2021-12-01T13:51:49.198Z] 

[2021-12-01T13:51:49.198Z] goroutine 3346 [running]:

[2021-12-01T13:51:49.198Z] testing.(*M).startAlarm.func1()

[2021-12-01T13:51:49.198Z] 	/usr/local/go/src/testing/testing.go:1700 +0x11f

[2021-12-01T13:51:49.198Z] created by time.goFunc

[2021-12-01T13:51:49.198Z] 	/usr/local/go/src/time/sleep.go:180 +0x52

[2021-12-01T13:51:49.198Z] 

```

**Comment by hi-rustin** [comment]
It seems like it hasn't happened again for a long time, so close it.
