### ISSUE TITLE
Flaking Test：TestClientSendAnomalies

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#3945]
### Which jobs are flaking?

https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/5639/tests/

### Which test(s) are flaking?

Test：TestClientSendAnomalies

### Jenkins logs or GitHub Actions link

```log
[2021/12/17 17:21:29.625 +08:00] [WARN] [client.go:167] ["peer message client detected error, restarting"] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/juju_adaptor.go:15\ngithub.com/pingcap/ticdc/pkg/p2p.(*MessageClient).runTx\n\t/home/jenkins/agent/workspace/atom-ut/ticdc/pkg/p2p/client.go:232\ngithub.com/pingcap/ticdc/pkg/p2p.(*MessageClient).run.func1\n\t/home/jenkins/agent/workspace/atom-ut/ticdc/pkg/p2p/client.go:199\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
[2021/12/17 17:21:29.626 +08:00] [INFO] [client.go:116] ["peer message client exited"] [addr=] [capture-id=node-2] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/juju_adaptor.go:15\ngithub.com/pingcap/ticdc/pkg/p2p.(*MessageClient).Run\n\t/home/jenkins/agent/workspace/atom-ut/ticdc/pkg/p2p/client.go:133\ngithub.com/pingcap/ticdc/pkg/p2p.TestClientSendAnomalies.func4\n\t/home/jenkins/agent/workspace/atom-ut/ticdc/pkg/p2p/client_test.go:327\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
    client_test.go:335: 
        	Error Trace:	client_test.go:335
        	Error:      	Expect "[CDC:ErrPeerMessageClientClosed]peer-to-peer message client has been closed" to match ".*ErrPeerMessageSendTryAgain.*"
        	Test:       	TestClientSendAnomalies
--- FAIL: TestClientSendAnomalies (0.00s)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by overvenus** [comment]
Another failed case

```log
=== RUN   TestClientSendAnomalies
    client_test.go:347: 
        	Error Trace:	client_test.go:347
        	Error:      	An error is expected but got nil.
        	Test:       	TestClientSendAnomalies
--- FAIL: TestClientSendAnomalies (0.10s)
```

**Comment by overvenus** [comment]
Another failed case

```
=== RUN   TestClientSendAnomalies
panic: 
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("Flush").Return(...) first, or remove the Flush() call.
	This method was unexpected:
		Flush()
		
	at: [client_test.go:45 client.go:319 client.go:211 client.go:199 errgroup.go:57 asm_amd64.s:1371]
goroutine 97 [running]:
github.com/stretchr/testify/mock.(*Mock).fail(0xc00054c180, 0x1432bd1, 0xc1, 0xc000497280, 0x4, 0x4)
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x21f
github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc00054c180, 0x18fd8d4, 0x5, 0x0, 0x0, 0x0, 0xc0004970c0, 0x4, 0x4)
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:418 +0xea5
github.com/stretchr/testify/mock.(*Mock).Called(0xc00054c180, 0x0, 0x0, 0x0, 0x10000c000133640, 0x4b846a, 0xc000544450)
	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x1ee
github.com/pingcap/tiflow/pkg/p2p.(*mockClientBatchSender).Flush(0xc00054c180, 0x1, 0xc000000002)
	/home/jenkins/agent/workspace/atom-ut/tiflow/pkg/p2p/client_test.go:45 +0x50
github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).retrySending(0xc0004587e0, 0x17aa8f8, 0xc00053e9c0, 0x17b05b0, 0xc0005b2580, 0x0, 0x0)
	/home/jenkins/agent/workspace/atom-ut/tiflow/pkg/p2p/client.go:319 +0x97c
github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).runTx(0xc0004587e0, 0x17aa8f8, 0xc00053e9c0, 0x17b05b0, 0xc0005b2580, 0x0, 0x0)
	/home/jenkins/agent/workspace/atom-ut/tiflow/pkg/p2p/client.go:211 +0xad
github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).run.func1(0x0, 0x0)
	/home/jenkins/agent/workspace/atom-ut/tiflow/pkg/p2p/client.go:199 +0x11b
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0005448d0, 0xc00053ea00)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x95
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x74
```

**Comment by overvenus** [comment]
Another case https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-348

```
[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-348)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-349)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-350)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-351)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-352)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-353)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-354)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-355)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-356)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-357)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-358)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-359)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-360)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-361)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-362)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-363)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-364)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-365)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-366)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-367)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-368)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-369)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-370)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-371)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-372)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-373)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-374)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/2643/pipeline/#step-49-log-375)[2022-02-22T16:39:15.237Z] === Failed

[2022-02-22T16:39:15.237Z] === FAIL: pkg/p2p TestClientSendAnomalies (unknown)

[2022-02-22T16:39:15.237Z] panic: 

[2022-02-22T16:39:15.237Z] assert: mock: I don't know what to return because the method call was unexpected.

[2022-02-22T16:39:15.237Z] 	Either do Mock.On("Flush").Return(...) first, or remove the Flush() call.

[2022-02-22T16:39:15.237Z] 	This method was unexpected:

[2022-02-22T16:39:15.237Z] 		Flush()

[2022-02-22T16:39:15.237Z] 		

[2022-02-22T16:39:15.237Z] 	at: [client_test.go:45 client.go:319 client.go:211 client.go:199 errgroup.go:57 asm_amd64.s:1371]

[2022-02-22T16:39:15.237Z] 

[2022-02-22T16:39:15.237Z] goroutine 116 [running]:

[2022-02-22T16:39:15.237Z] github.com/stretchr/testify/mock.(*Mock).fail(0xc00068e720, 0x1441169, 0xc1, 0xc00067c9c0, 0x4, 0x4)

[2022-02-22T16:39:15.237Z] 	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x21f

[2022-02-22T16:39:15.237Z] github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc00068e720, 0x190e5a8, 0x5, 0x0, 0x0, 0x0, 0xc00067c800, 0x4, 0x4)

[2022-02-22T16:39:15.237Z] 	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:418 +0xea5

[2022-02-22T16:39:15.237Z] github.com/stretchr/testify/mock.(*Mock).Called(0xc00068e720, 0x0, 0x0, 0x0, 0x10000c0000c9640, 0x4b846a, 0xc000614720)

[2022-02-22T16:39:15.237Z] 	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x1ee

[2022-02-22T16:39:15.237Z] github.com/pingcap/tiflow/pkg/p2p.(*mockClientBatchSender).Flush(0xc00068e720, 0x1, 0xc000000002)

[2022-02-22T16:39:15.237Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client_test.go:45 +0x50

[2022-02-22T16:39:15.237Z] github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).retrySending(0xc00041aaf0, 0x17b96f8, 0xc00067c640, 0x17bf410, 0xc00028c6c0, 0x1, 0x2)

[2022-02-22T16:39:15.237Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client.go:319 +0x97c

[2022-02-22T16:39:15.237Z] github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).runTx(0xc00041aaf0, 0x17b96f8, 0xc00067c640, 0x17bf410, 0xc00028c6c0, 0x0, 0x0)

[2022-02-22T16:39:15.237Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client.go:211 +0xad

[2022-02-22T16:39:15.237Z] github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).run.func1(0x0, 0x0)

[2022-02-22T16:39:15.237Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client.go:199 +0x11b

[2022-02-22T16:39:15.237Z] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000423050, 0xc00067c680)

[2022-02-22T16:39:15.237Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x95

[2022-02-22T16:39:15.237Z] created by golang.org/x/sync/errgroup.(*Group).Go

[2022-02-22T16:39:15.237Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x74
```

**Comment by overvenus** [comment]
It fails again. https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-352

```log
[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-350)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-351)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-352)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-353)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-354)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-355)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-356)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-357)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-358)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-359)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-360)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-361)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-362)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-363)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-364)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-365)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-366)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-367)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-368)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-369)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-370)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-371)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-372)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-373)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-374)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-375)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/3818/pipeline/#step-49-log-376)[2022-03-03T14:27:21.788Z] === Failed

[2022-03-03T14:27:21.788Z] === FAIL: pkg/p2p TestClientSendAnomalies (unknown)

[2022-03-03T14:27:21.788Z] panic: 

[2022-03-03T14:27:21.788Z] assert: mock: I don't know what to return because the method call was unexpected.

[2022-03-03T14:27:21.788Z] 	Either do Mock.On("Append").Return(...) first, or remove the Append() call.

[2022-03-03T14:27:21.788Z] 	This method was unexpected:

[2022-03-03T14:27:21.788Z] 		Append(*p2p.MessageEntry)

[2022-03-03T14:27:21.788Z] 		0: &p2p.MessageEntry{Topic:"test-topic", Content:[]uint8{0x7b, 0x22, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x31, 0x7d}, Sequence:1, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}

[2022-03-03T14:27:21.788Z] 	at: [client_test.go:39 client.go:263 client.go:199 errgroup.go:57 asm_amd64.s:1371]

[2022-03-03T14:27:21.788Z] 

[2022-03-03T14:27:21.788Z] goroutine 103 [running]:

[2022-03-03T14:27:21.788Z] github.com/stretchr/testify/mock.(*Mock).fail(0xc0005a8660, 0x14411f8, 0xc1, 0xc0006ae180, 0x4, 0x4)

[2022-03-03T14:27:21.788Z] 	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:254 +0x21f

[2022-03-03T14:27:21.788Z] github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0005a8660, 0x190e5e6, 0x6, 0xc0000cedd0, 0x1, 0x1, 0xc0006ae000, 0x4, 0x4)

[2022-03-03T14:27:21.788Z] 	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:418 +0xea5

[2022-03-03T14:27:21.788Z] github.com/stretchr/testify/mock.(*Mock).Called(0xc0005a8660, 0xc0000cedd0, 0x1, 0x1, 0xc0000324e0, 0x140b7e5, 0xf)

[2022-03-03T14:27:21.788Z] 	/go/pkg/mod/github.com/stretchr/testify@v1.7.0/mock/mock.go:383 +0x1ee

[2022-03-03T14:27:21.788Z] github.com/pingcap/tiflow/pkg/p2p.(*mockClientBatchSender).Append(0xc0005a8660, 0xc0005c2910, 0xc00015c100, 0x2)

[2022-03-03T14:27:21.788Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client_test.go:39 +0xa5

[2022-03-03T14:27:21.788Z] github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).runTx(0xc00047f490, 0x17b9778, 0xc000566800, 0x17bf490, 0xc00057f440, 0x0, 0x0)

[2022-03-03T14:27:21.788Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client.go:263 +0x997

[2022-03-03T14:27:21.788Z] github.com/pingcap/tiflow/pkg/p2p.(*MessageClient).run.func1(0x0, 0x0)

[2022-03-03T14:27:21.788Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/p2p/client.go:199 +0x11b

[2022-03-03T14:27:21.788Z] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00022c3c0, 0xc000566840)

[2022-03-03T14:27:21.788Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x95

[2022-03-03T14:27:21.788Z] created by golang.org/x/sync/errgroup.(*Group).Go

[2022-03-03T14:27:21.788Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x74

[2022-03-03T14:27:21.788Z]
```
