### ISSUE TITLE
DM worker panic in chaos test

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tiflow#4489]
### What did you do?

run chaos test https://github.com/pingcap/tiflow/actions/runs/1751777535

### What did you expect to see?

test succeed

### What did you see instead?

test failed
worker panic with log
```
[2022/01/26 16:16:02.563 +00:00] [INFO] [subtask.go:253] ["start to run"] [subtask=task_optimistic] [unit=Load]
[2022/01/26 16:16:02.563 +00:00] [INFO] [lightning.go:277] ["lightning load start"] [task=task_optimistic] [unit=lightning-load]
[2022/01/26 16:16:02.577 +00:00] [INFO] [util.go:179] ["put load worker in etcd"] [task=task_optimistic] [source=replica-01] [worker=dm-worker-0]
[2022/01/26 16:16:02.659 +00:00] [INFO] [checkpoint.go:570] ["initial checkpoint record"] [component="lightning checkpoint database list"] [task=task_optimistic] [source=replica-01]
[2022/01/26 16:16:02.773 +00:00] [INFO] [checkpoint.go:590] ["update lightning loader status"] [component="lightning checkpoint database list"] [task=task_optimistic] [source=replica-01] [status=running]
[2022/01/26 16:16:03.902 +00:00] [INFO] [printer.go:54] ["Welcome to dm-worker"] ["Release Version"=v5.4.0-master] ["Git Commit Hash"=910bcd86364701233347e0d183bc201feda74cd0] ["Git Branch"=HEAD] ["UTC Build Time"="2022-01-26 16:09:55"] ["Go Version"="go version go1.16.13 linux/amd64"]
[dm-worker-1_default_dm-worker-f57db5c5baeeb6a1e4fad376d3723b81eaa1b954ea33e86f5dfbd67b548a8bbe.log](https://github.com/pingcap/tiflow/files/7947443/dm-worker-1_default_dm-worker-f57db5c5baeeb6a1e4fad376d3723b81eaa1b954ea33e86f5dfbd67b548a8bbe.log)

```
```
{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2022-01-26T16:16:02.915207495Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2bcc8f2]\n","stream":"stderr","time":"2022-01-26T16:16:02.915222595Z"}
{"log":"\n","stream":"stderr","time":"2022-01-26T16:16:02.915226296Z"}
{"log":"goroutine 1596 [running]:\n","stream":"stderr","time":"2022-01-26T16:16:02.915229596Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/checkpoints.(*TableCheckpoint).Apply(0x0, 0xc00a520930)\n","stream":"stderr","time":"2022-01-26T16:16:02.915285898Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/checkpoints/checkpoints.go:362 +0x52\n","stream":"stderr","time":"2022-01-26T16:16:02.9153269Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/web.(*checkpointsMap).update(0x5e04c98, 0xc00a3d96e0, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2022-01-26T16:16:02.9153323Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/web/progress.go:60 +0x2b2\n","stream":"stderr","time":"2022-01-26T16:16:02.915336Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/web.BroadcastCheckpointDiff(0xc00a3d96e0)\n","stream":"stderr","time":"2022-01-26T16:16:02.9153396Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/web/progress.go:157 +0x3b\n","stream":"stderr","time":"2022-01-26T16:16:02.915360601Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).listenCheckpointUpdates.func1(0xc000739920, 0xc00914b358, 0xc00915c290, 0xc005661ed8, 0xc005812140)\n","stream":"stderr","time":"2022-01-26T16:16:02.915364301Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1004 +0x1bf\n","stream":"stderr","time":"2022-01-26T16:16:02.915367802Z"}
{"log":"created by github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).listenCheckpointUpdates\n","stream":"stderr","time":"2022-01-26T16:16:02.915538809Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:987 +0x17f\n","stream":"stderr","time":"2022-01-26T16:16:02.915545909Z"}
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by GMHDBJD** [comment]
full log 
[Archive.zip](https://github.com/pingcap/tiflow/files/7947462/Archive.zip)
