### ISSUE TITLE
unstable test client_test

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#4567]

**Comment by 3AceShowHand** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/19861/pipeline

**Comment by hi-rustin** [comment]
another case: 
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline
```log
[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-444)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-445)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-446)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-447)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-448)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-449)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-450)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-451)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-452)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-453)[](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/22641/pipeline#step-58-log-454)[2022-03-16T07:58:18.733Z] goleak: Errors on successful test run: found unexpected goroutines:

[2022-03-16T07:58:18.733Z] [Goroutine 2564 in state chan send, with github.com/pingcap/tiflow/cdc/kv.TestRegionWorkerExitWhenIsIdle.func1.1 on top of the stack:

[2022-03-16T07:58:18.733Z] goroutine 2564 [chan send]:

[2022-03-16T07:58:18.733Z] github.com/pingcap/tiflow/cdc/kv.TestRegionWorkerExitWhenIsIdle.func1.1(0xc0043be0c0)

[2022-03-16T07:58:18.733Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:3308 +0x45

[2022-03-16T07:58:18.733Z] github.com/pingcap/tiflow/cdc/kv.TestRegionWorkerExitWhenIsIdle.func1(0x6543878, 0xc0043893f0)

[2022-03-16T07:58:18.733Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:3317 +0x260

[2022-03-16T07:58:18.733Z] github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed.func1(0xc0085980f0, 0x6543878, 0xc0043893f0)

[2022-03-16T07:58:18.733Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:230 +0x62

[2022-03-16T07:58:18.733Z] created by github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed

[2022-03-16T07:58:18.733Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:229 +0x38f

[2022-03-16T07:58:18.733Z] ]
```

**Comment by zhaoxinyu** [comment]
another case: https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/9536/pipeline/

**Comment by asddongmen** [comment]
[2022-05-05T09:52:10.744Z] goleak: Errors on successful test run: found unexpected goroutines:

[2022-05-05T09:52:10.744Z] [Goroutine 2351 in state chan send, with github.com/pingcap/tiflow/cdc/kv.TestRegionWorkerExitWhenIsIdle.func1.1 on top of the stack:

[2022-05-05T09:52:10.744Z] goroutine 2351 [chan send]:

[2022-05-05T09:52:10.744Z] github.com/pingcap/tiflow/cdc/kv.TestRegionWorkerExitWhenIsIdle.func1.1()

[2022-05-05T09:52:10.744Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:3399 +0x36

[2022-05-05T09:52:10.744Z] github.com/pingcap/tiflow/cdc/kv.TestRegionWorkerExitWhenIsIdle.func1({0x60b1eb8, 0xc008179550})

[2022-05-05T09:52:10.744Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:3408 +0x22b

[2022-05-05T09:52:10.744Z] github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed.func1()

[2022-05-05T09:52:10.744Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:207 +0x62

[2022-05-05T09:52:10.744Z] created by github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed

[2022-05-05T09:52:10.744Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/kv/client_test.go:206 +0x13b

[2022-05-05T09:52:10.744Z] ]

[2022-05-05T09:52:10.744Z] FAIL	github.com/pingcap/tiflow/cdc/kv	72.667s

**Comment by CharlesCheung96** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/25590/pipeline
