### ISSUE TITLE
Flaky test:   panic: Log in goroutine after TestGetOwnerRevision has completed

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#4856]
### Which jobs are flaking?

ut

### Which test(s) are flaking?

TestGetOwnerRevision

### Jenkins logs or GitHub Actions link

https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/
```log
(https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-366)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-367)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-368)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-369)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-370)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-371)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-372)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-373)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-374)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-375)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-376)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-377)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-378)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-379)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-380)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-381)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-382)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-383)[](https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/5094/pipeline/#step-49-log-384)[2022-03-11T05:13:48.954Z] panic: Log in goroutine after TestGetOwnerRevision has completed

[2022-03-11T05:13:48.954Z] 

[2022-03-11T05:13:48.954Z] goroutine 1059 [running]:

[2022-03-11T05:13:48.954Z] testing.(*common).logDepth(0xc001287980, 0xc000d7e308, 0x6, 0x3)

[2022-03-11T05:13:48.954Z] 	/usr/local/go/src/testing/testing.go:764 +0x80e

[2022-03-11T05:13:48.954Z] testing.(*common).log(...)

[2022-03-11T05:13:48.954Z] 	/usr/local/go/src/testing/testing.go:746

[2022-03-11T05:13:48.954Z] testing.(*common).Log(0xc001287980, 0xc0000d3650, 0x1, 0x1)

[2022-03-11T05:13:48.954Z] 	/usr/local/go/src/testing/testing.go:785 +0x78

[2022-03-11T05:13:48.954Z] github.com/pingcap/tiflow/pkg/etcd.(*etcdTester).setUpTest.func1(0x0, 0x0)

[2022-03-11T05:13:48.954Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/etcd/etcd_test.go:74 +0xa7

[2022-03-11T05:13:48.954Z] github.com/pingcap/tiflow/pkg/util.HandleErr(0x379e970, 0xc00135b700, 0xc000f2db60, 0xc0003fba60)

[2022-03-11T05:13:48.954Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/util/test_helper.go:42 +0x67

[2022-03-11T05:13:48.954Z] github.com/pingcap/tiflow/pkg/util.HandleErrWithErrGroup.func1(0xc0000d3750, 0x2)

[2022-03-11T05:13:48.954Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/pkg/util/test_helper.go:51 +0x5d

[2022-03-11T05:13:48.954Z] golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00082b7a0, 0xc00082b7d0)

[2022-03-11T05:13:48.954Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x95

[2022-03-11T05:13:48.954Z] created by golang.org/x/sync/errgroup.(*Group).Go

[2022-03-11T05:13:48.954Z] 	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x74
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by zhaoxinyu** [comment]
An other case: https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/23759/pipeline
[2022-04-06T05:15:36.452Z] --- FAIL: TestGetOwnerRevision (18.52s)

[2022-04-06T05:15:36.452Z]     etcd_test.go:422: 

[2022-04-06T05:15:36.452Z]         	Error Trace:	etcd_test.go:422

[2022-04-06T05:15:36.452Z]         	            				asm_amd64.s:1571

[2022-04-06T05:15:36.452Z]         	Error:      	"context deadline exceeded" does not contain "context canceled"

[2022-04-06T05:15:36.452Z]         	Test:       	TestGetOwnerRevision

[2022-04-06T05:15:36.452Z]     etcd_test.go:422: 

[2022-04-06T05:15:36.452Z]         	Error Trace:	etcd_test.go:422

[2022-04-06T05:15:36.452Z]         	            				asm_amd64.s:1571

[2022-04-06T05:15:36.452Z]         	Error:      	"context deadline exceeded" does not contain "context canceled"

[2022-04-06T05:15:36.452Z]         	Test:       	TestGetOwnerRevision

[2022-04-06T05:15:36.452Z]     etcd_test.go:422: 

[2022-04-06T05:15:36.452Z]         	Error Trace:	etcd_test.go:422

[2022-04-06T05:15:36.452Z]         	            				asm_amd64.s:1571

[2022-04-06T05:15:36.452Z]         	Error:      	"context deadline exceeded" does not contain "context canceled"

[2022-04-06T05:15:36.452Z]         	Test:       	TestGetOwnerRevision

[2022-04-06T05:15:36.452Z]     etcd_test.go:74: <nil>

[2022-04-06T05:15:36.452Z]     etcd_test.go:74: <nil>
