### ISSUE TITLE
Goroutine leak in mysql sink

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#5356]
### Which jobs are flaking?

leak_test

### Which test(s) are flaking?

mysql_test

### Jenkins logs or GitHub Actions link

```log
[2022-05-07T06:20:02.424Z] PASS

[2022-05-07T06:20:02.424Z] goleak: Errors on successful test run: found unexpected goroutines:

[2022-05-07T06:20:02.424Z] [Goroutine 349 in state semacquire, with sync.runtime_Semacquire on top of the stack:

[2022-05-07T06:20:02.424Z] goroutine 349 [semacquire]:

[2022-05-07T06:20:02.424Z] sync.runtime_Semacquire(0xc000c8e3b0?)

[2022-05-07T06:20:02.424Z] 	/usr/local/go/src/runtime/sema.go:56 +0x25

[2022-05-07T06:20:02.424Z] sync.(*WaitGroup).Wait(0xc000c8e3a8)

[2022-05-07T06:20:02.424Z] 	/usr/local/go/src/sync/waitgroup.go:136 +0x9c

[2022-05-07T06:20:02.425Z] github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).notifyAndWaitExec.func1()

[2022-05-07T06:20:02.425Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:456 +0x45

[2022-05-07T06:20:02.425Z] created by github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).notifyAndWaitExec

[2022-05-07T06:20:02.425Z] 	/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:455 +0x31b

[2022-05-07T06:20:02.425Z] ]

[2022-05-07T06:20:02.425Z] FAIL	github.com/pingcap/tiflow/cdc/sink/mysql	8.547s
```

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/25186/pipeline

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by zhaoxinyu** [comment]
another case: https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/25250/pipeline

**Comment by overvenus** [comment]
another case: https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_leak_test/detail/cdc_ghpr_leak_test/25392/pipeline#step-72-log-341

**Comment by CharlesCheung96** [comment]
```
[2022-05-11T05:37:13.408Z] --- FAIL: TestMySQLSinkFlushResolvedTs (0.46s)

[2022-05-11T05:37:13.408Z]     leaks.go:78: found unexpected goroutines:

[2022-05-11T05:37:13.408Z]         [Goroutine 297 in state semacquire, with sync.runtime_Semacquire on top of the stack:

[2022-05-11T05:37:13.408Z]         goroutine 297 [semacquire]:

[2022-05-11T05:37:13.408Z]         sync.runtime_Semacquire(0xc00105a2b0?)

[2022-05-11T05:37:13.408Z]         	/usr/local/go/src/runtime/sema.go:56 +0x25

[2022-05-11T05:37:13.408Z]         sync.(*WaitGroup).Wait(0xc00105a2a8)

[2022-05-11T05:37:13.408Z]         	/usr/local/go/src/sync/waitgroup.go:136 +0x9c

[2022-05-11T05:37:13.408Z]         github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).notifyAndWaitExec.func1()
```

**Comment by asddongmen** [comment]
This issue is stale.
