### ISSUE TITLE
mysqlSink can deadlock when executing DML results in errors

### ISSUE THREAD

**Issue by liuzix** [pingcap/tiflow#5847]
```
goroutine 765 [chan receive]:
github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSinkWorker).cleanup(0xc001c60580)
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql_worker.go:161 +0x58
github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).createSinkWorkers.func1()
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:427 +0x347
created by github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).createSinkWorkers
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:418 +0x207

goroutine 940 [select]:
github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).notifyAndWaitExec(0xc00294c100, {0x79c0528, 0xc001c60340})
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:454 +0x3e5
github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).dispatchAndExecTxns(0xc00294c100, {0x79c0528, 0xc001c60340}, 0x0?)
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:498 +0x2b3
github.com/pingcap/tiflow/cdc/sink/mysql.(*mysqlSink).flushRowChangedEvents(0xc00294c100, {0x79c0528, 0xc001c60340})
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:274 +0x3d2
created by github.com/pingcap/tiflow/cdc/sink/mysql.NewMySQLSink
	/go/src/github.com/pingcap/tiflow/cdc/sink/mysql/mysql.go:212 +0x22bc
```

MySQL sink fails to handle errors correctly, leading to deadlocks.

**Comment by hi-rustin** [comment]
The scope of this issue.
1. it is indeed a bug
2. it only appeared now because buffersink was deleted, resulting in a deadlock in TablePipeline's architecture
3. there is no deadlock under TableActor

**Comment by hi-rustin** [comment]
Buffersink is only removed on 6.1 and master, so other branches don't have this problem either.
