### ISSUE TITLE
job manager enters unexpected state

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#5874]
### What did you do?

run chaos test, ref: https://github.com/pingcap/tiflow/runs/6875901896?check_suite_focus=true

### What did you see instead?

Job manager in the server master leader met error, but it didn't exit and recover

first error
```go
[2022/06/14 07:57:41.021 +00:00] [WARN] [center.go:53] ["More than one error is received"] [error="[DFLOW:ErrMasterTooManyPendingEvents]master has too many pending events"] [errorVerbose="[DFLOW:ErrMasterTooManyPendingEvents]master has too many pending events\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/framework/master.(*WorkerManager).enqueueEvent\n\tgithub.com/pingcap/tiflow/engine/framework/master/worker_manager.go:576\ngithub.com/pingcap/tiflow/engine/framework/master.(*WorkerManager).OnWorkerStatusUpdateMessage\n\tgithub.com/pingcap/tiflow/engine/framework/master/worker_manager.go:425\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseMaster).registerMessageHandlers.func2\n\tgithub.com/pingcap/tiflow/engine/framework/master.go:385\ngithub.com/pingcap/tiflow/pkg/p2p.(*MessageServer).AddHandler.func1\n\tgithub.com/pingcap/tiflow/pkg/p2p/server.go:431\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultEventHandle).AddEvent.func2\n\tgithub.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:140\ngithub.com/pingcap/tiflow/pkg/workerpool.(*worker).run\n\tgithub.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:377\ngithub.com/pingcap/tiflow/pkg/workerpool.(*defaultPoolImpl).Run.func1\n\tgithub.com/pingcap/tiflow/pkg/workerpool/pool_impl.go:67\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/06/14 07:57:41.420 +00:00] [INFO] [master.go:348] ["Heartbeat Ping received"] [msg="{\"send-time\":729816742093,\"from-worker-id\":\"71d976f1-e641-4968-bbb0-3727dff153c5\",\"epoch\":4,\"is-finished\":false}"] [master-id=dataflow-engine-job-manager]
```

detail logs:

[chaos-base-logs.network-emulation-dataflow.zip](https://github.com/pingcap/tiflow/files/8899088/chaos-base-logs.network-emulation-dataflow.zip)

### Versions of the cluster

Dataflow Engine version (run `df-master -V` or `df-executor -V`):

master@https://github.com/pingcap/tiflow/commit/65e67fc4b2155ca41a0e907f586ac370e67cd99c

**Comment by amyangfei** [comment]
Reproduced in another case: https://github.com/pingcap/tiflow/runs/6931719167?check_suite_focus=true

Observed job master fails 

```go
[2022/06/17 07:08:11.066 +00:00] [WARN] [center.go:53] ["More than one error is received"] [error="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(dataflow-engine-job-manager) having timed out"] [errorVerbose="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(dataflow-engine-job-manager) having timed out\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).runWatchDog\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:537\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).startBackgroundTasks.func2\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:494\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/06/17 07:08:11.080 +00:00] [INFO] [task_runner.go:270] ["Task stopped"] [id=e67f3666-abfd-4f2e-a98b-9a66527520ce] [error="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(dataflow-engine-job-manager) having timed out"] [errorVerbose="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(dataflow-engine-job-manager) having timed out\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).runWatchDog\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:537\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).startBackgroundTasks.func2\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:494\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/06/17 07:08:26.099 +00:00] [WARN] [center.go:53] ["More than one error is received"] [error="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(e67f3666-abfd-4f2e-a98b-9a66527520ce) having timed out"] [errorVerbose="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(e67f3666-abfd-4f2e-a98b-9a66527520ce) having timed out\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).runWatchDog\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:537\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).startBackgroundTasks.func2\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:494\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/06/17 07:08:26.100 +00:00] [WARN] [center.go:53] ["More than one error is received"] [error="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(e67f3666-abfd-4f2e-a98b-9a66527520ce) having timed out"] [errorVerbose="[DFLOW:ErrWorkerSuicide]worker has committed suicide due to master(e67f3666-abfd-4f2e-a98b-9a66527520ce) having timed out\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).runWatchDog\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:537\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).startBackgroundTasks.func2\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:494\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
```

But job manager doesn't failover.

**Comment by amyangfei** [comment]
Located the root cause, if etcd leader changes, `runLeaderService` doesn't exit because of the remaining goroutines of gc managers.

```go
goroutine 9046 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0x40d6c5?)
        runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x307?)
        sync/waitgroup.go:136 +0x52
golang.org/x/sync/errgroup.(*Group).Wait(0xc000b7f980)
        golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:52 +0x27
github.com/pingcap/tiflow/engine/servermaster.(*Server).runLeaderService.func9()
        github.com/pingcap/tiflow/engine/servermaster/server.go:749 +0x2f
github.com/pingcap/tiflow/engine/servermaster.(*Server).runLeaderService(0xc0009fa180, {0x35db498, 0xc000994620})
        github.com/pingcap/tiflow/engine/servermaster/server.go:775 +0x17a7
github.com/pingcap/tiflow/engine/servermaster.(*Server).leaderLoop(0xc0009fa180, {0x35da548, 0xc0024cbc80})
        github.com/pingcap/tiflow/engine/servermaster/campaign.go:106 +0x2c3
github.com/pingcap/tiflow/engine/servermaster.(*Server).Run.func2()
        github.com/pingcap/tiflow/engine/servermaster/server.go:484 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:71 +0xa5
```
