### ISSUE TITLE
DM: dm panic when resume task which is in dump stage

### ISSUE THREAD

**Issue by WizardXiao** [pingcap/tiflow#5970]
### What did you do?

resume task which is in dump stage

### What did you expect to see?

normal resume

### What did you see instead?

```
panic: duplicate metrics collector registration attempted

goroutine 3375 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc001532fa0?, {0xc00f74f290, 0x1, 0x68f42fc?})
        /home/cuixiaoyuan/go/pkg/mod/github.com/prometheus/client_golang@v1.12.2/prometheus/registry.go:403 +0xa7
github.com/pingcap/tidb/dumpling/export.(*metrics).registerTo(0xc004e9ac40, {0x7ec3440, 0xc0005ac910})
        /home/cuixiaoyuan/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220617092035-96526518b4e8/dumpling/export/metrics.go:96 +0xce
github.com/pingcap/tidb/dumpling/export.NewDumper({0x7ec9148, 0xc004e9abc0}, 0xc000f49180)
        /home/cuixiaoyuan/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220617092035-96526518b4e8/dumpling/export/dump.go:85 +0x43c
github.com/pingcap/tiflow/dm/dumpling.(*Dumpling).Process(0xc00409cff0, {0x7ec9148, 0xc0041d3f00}, 0xc004190a80?)
        /home/cuixiaoyuan/workspace/enhance-dmctl-task/dm/dumpling/dumpling.go:163 +0xa5b
github.com/pingcap/tiflow/dm/dumpling.(*Dumpling).Resume(0xc00409cff0, {0x7ec9148, 0xc0041d3f00}, 0x179351a?)
        /home/cuixiaoyuan/workspace/enhance-dmctl-task/dm/dumpling/dumpling.go:244 +0xde
created by github.com/pingcap/tiflow/dm/dm/worker.(*SubTask).Resume
        /home/cuixiaoyuan/workspace/enhance-dmctl-task/dm/dm/worker/subtask.go:651 +0x6bc
```

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by WizardXiao** [comment]
add some warn log to make sure this issue and find out it caused by error occurred during `NewDumper`. 
```
2022/06/23 14:54:46.931 +08:00] [WARN] [dumpling.go:175] ["error occurred during NewDumper"] [error="sql: SELECT version();: context canceled"] [errorVerbose="context canceled\nsql: SELECT version();\ngithub.com/pingcap/tidb/br/pkg/version.FetchVersion\n\t/home/cuixiaoyuan/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220617092035-96526518b4e8/br/pkg/version/version.go:269\ngithub.com/pingcap/tidb/dumpling/export.detectServerInfo\n\t/home/cuixiaoyuan/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220617092035-96526518b4e8/dumpling/export/dump.go:1309\ngithub.com/pingcap/tidb/dumpling/export.runSteps\n\t/home/cuixiaoyuan/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220617092035-96526518b4e8/dumpling/export/dump.go:1236\ngithub.com/pingcap/tidb/dumpling/export.NewDumper\n\t/home/cuixiaoyuan/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220617092035-96526518b4e8/dumpling/export/dump.go:94\ngithub.com/pingcap/tiflow/dm/dumpling.(*Dumpling).Process\n\t/home/cuixiaoyuan/workspace/enhance-dmctl-task/dm/dumpling/dumpling.go:163\ngithub.com/pingcap/tiflow/dm/dumpling.(*Dumpling).Resume\n\t/home/cuixiaoyuan/workspace/enhance-dmctl-task/dm/dumpling/dumpling.go:246\nruntime.goexit\n\t/home/cuixiaoyuan/goroot/src/runtime/asm_amd64.s:1571"]
```
[#35649](https://github.com/pingcap/tidb/issues/35649) unregister metrics if `NewDumper` is fail, so there will be ok after update tidb reference.
