### ISSUE TITLE
DM worker can't exit due to relay is working

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#6211]
### Which jobs are flaking?

DM-IT

### Which test(s) are flaking?

ha_cases_1

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/7525/pipeline

```
[2022-07-07T05:47:20.958Z] disable isolate dm-worker4
[2022-07-07T05:47:20.958Z] kill dm-worker4
[2022-07-07T05:47:21.227Z] process dm-worker4 already exit
[2022-07-07T05:47:21.227Z] wait for port 18262 offline the 1-th time
...
[2022-07-07T05:47:41.871Z] port 18262 check offline timeout
```

```

[2022-07-07T05:47:42.610Z] + echo /tmp/dm_test/goroutines/stack/log/worker-18262.log
[2022-07-07T05:47:42.610Z] /tmp/dm_test/goroutines/stack/log/worker-18262.log
[2022-07-07T05:47:42.610Z] + cat /tmp/dm_test/goroutines/stack/log/worker-18262.log
[2022-07-07T05:47:42.610Z] goroutine 312 [running]:
[2022-07-07T05:47:42.610Z] runtime/pprof.writeGoroutineStacks({0x7f45e80, 0xc0011bc000})
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/runtime/pprof/pprof.go:694 +0x85
[2022-07-07T05:47:42.610Z] runtime/pprof.writeGoroutine({0x7f45e80, 0xc0011bc000}, 0x2)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/runtime/pprof/pprof.go:683 +0x4b
[2022-07-07T05:47:42.610Z] runtime/pprof.(*Profile).WriteTo(0xa0c6120, {0x7f45e80, 0xc0011bc000}, 0xc?)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/runtime/pprof/pprof.go:332 +0x1b1
[2022-07-07T05:47:42.610Z] net/http/pprof.handler.ServeHTTP({0xc000ea4bb1, 0x9}, {0x7f63900, 0xc0011bc000}, 0x1dd8ac5?)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/pprof/pprof.go:253 +0x57f
[2022-07-07T05:47:42.610Z] net/http/pprof.Index({0x7f63900?, 0xc0011bc000}, 0xc000ab3200)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/pprof/pprof.go:371 +0x3a5
[2022-07-07T05:47:42.610Z] net/http.HandlerFunc.ServeHTTP(0x6b20bd8, {0x7f63900, 0xc0011bc000}, 0xc000fb73b0?)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/server.go:2084 +0x4e
[2022-07-07T05:47:42.610Z] net/http.(*ServeMux).ServeHTTP(0xc000ea4bbb?, {0x7f63900, 0xc0011bc000}, 0xc000ab3200)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/server.go:2462 +0xc6
[2022-07-07T05:47:42.610Z] net/http.serverHandler.ServeHTTP({0xc000fb73b0?}, {0x7f63900, 0xc0011bc000}, 0xc000ab3200)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/server.go:2916 +0x897
[2022-07-07T05:47:42.610Z] net/http.(*conn).serve(0xc0001ddc20, {0x7f66070, 0xc0010143f0})
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/server.go:1966 +0xbab
[2022-07-07T05:47:42.610Z] created by net/http.(*Server).Serve
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/net/http/server.go:3071 +0x80d
[2022-07-07T05:47:42.610Z] 
[2022-07-07T05:47:42.610Z] goroutine 1 [chan receive]:
[2022-07-07T05:47:42.610Z] testing.(*T).Run(0xc000230820, {0x69829d9, 0xb}, 0x6b1e380)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1487 +0x750
[2022-07-07T05:47:42.610Z] testing.runTests.func1(0x0?)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1839 +0x9a
[2022-07-07T05:47:42.610Z] testing.tRunner(0xc000230820, 0xc000dbfb68)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1439 +0x214
[2022-07-07T05:47:42.610Z] testing.runTests(0xc0010270e0?, {0xa0bb650, 0x1, 0x1}, {0x40?, 0x64013e0?, 0x0?})
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1837 +0x7e5
[2022-07-07T05:47:42.610Z] testing.(*M).Run(0xc0010270e0)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1719 +0xa72
[2022-07-07T05:47:42.610Z] main.main()
[2022-07-07T05:47:42.610Z] 	_testmain.go:703 +0x3ca
[2022-07-07T05:47:42.610Z] 
[2022-07-07T05:47:42.610Z] goroutine 81 [select]:
[2022-07-07T05:47:42.610Z] github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain(0x0?)
[2022-07-07T05:47:42.610Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:70 +0x39c
[2022-07-07T05:47:42.610Z] testing.tRunner(0xc0002309c0, 0x6b1e380)
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1439 +0x214
[2022-07-07T05:47:42.610Z] created by testing.(*T).Run
[2022-07-07T05:47:42.610Z] 	/usr/local/go/src/testing/testing.go:1486 +0x725
[2022-07-07T05:47:42.610Z] 
[2022-07-07T05:47:42.610Z] goroutine 30 [select]:
[2022-07-07T05:47:42.610Z] go.opencensus.io/stats/view.(*worker).start(0xc000ec4000)
[2022-07-07T05:47:42.610Z] 	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x177
[2022-07-07T05:47:42.610Z] created by go.opencensus.io/stats/view.init.0
[2022-07-07T05:47:42.610Z] 	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xf7
[2022-07-07T05:47:42.610Z] 
[2022-07-07T05:47:42.610Z] goroutine 47 [chan receive]:
[2022-07-07T05:47:42.610Z] github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
[2022-07-07T05:47:42.610Z] 	/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x8b
[2022-07-07T05:47:42.610Z] created by github.com/golang/glog.init.0
[2022-07-07T05:47:42.610Z] 	/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x265
[2022-07-07T05:47:42.610Z] 
[2022-07-07T05:47:42.610Z] goroutine 110 [select]:
[2022-07-07T05:47:42.610Z] github.com/pingcap/tiflow/dm/relay.(*relayPurger).run(0xc000ed8540)
[2022-07-07T05:47:42.610Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/purger.go:136 +0x253
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/relay.(*relayPurger).Start.func1()
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/purger.go:121 +0x85
[2022-07-07T05:47:42.611Z] created by github.com/pingcap/tiflow/dm/relay.(*relayPurger).Start
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/purger.go:119 +0x294
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 117 [IO wait]:
[2022-07-07T05:47:42.611Z] internal/poll.runtime_pollWait(0x7f81f9d89928, 0x72)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/runtime/netpoll.go:302 +0x89
[2022-07-07T05:47:42.611Z] internal/poll.(*pollDesc).wait(0xc00067ab98, 0x17ee301?, 0x0)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0xbd
[2022-07-07T05:47:42.611Z] internal/poll.(*pollDesc).waitRead(...)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
[2022-07-07T05:47:42.611Z] internal/poll.(*FD).Accept(0xc00067ab80)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x425
[2022-07-07T05:47:42.611Z] net.(*netFD).accept(0xc00067ab80)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/net/fd_unix.go:172 +0x4a
[2022-07-07T05:47:42.611Z] net.(*TCPListener).accept(0xc0012368d0)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/net/tcpsock_posix.go:139 +0x45
[2022-07-07T05:47:42.611Z] net.(*TCPListener).Accept(0xc0012368d0)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/net/tcpsock.go:288 +0x68
[2022-07-07T05:47:42.611Z] github.com/soheilhy/cmux.(*cMux).Serve(0xc0006a4000)
[2022-07-07T05:47:42.611Z] 	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:170 +0x122
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start(0xc000d068f0)
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:219 +0x1ec5
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/cmd/dm-worker.main()
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main.go:93 +0xa2f
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain.func3()
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:66 +0x2c
[2022-07-07T05:47:42.611Z] created by github.com/pingcap/tiflow/dm/cmd/dm-worker.TestRunMain
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/cmd/dm-worker/main_test.go:65 +0x332
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 118 [chan receive]:
[2022-07-07T05:47:42.611Z] gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc000efc1e0)
[2022-07-07T05:47:42.611Z] 	/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x65
[2022-07-07T05:47:42.611Z] created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
[2022-07-07T05:47:42.611Z] 	/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0xef
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 120 [syscall]:
[2022-07-07T05:47:42.611Z] os/signal.signal_recv()
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/runtime/sigqueue.go:151 +0x2f
[2022-07-07T05:47:42.611Z] os/signal.loop()
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x25
[2022-07-07T05:47:42.611Z] created by os/signal.Notify.func1.1
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/os/signal/signal.go:151 +0x51
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 108 [select]:
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/relay.reportRelayLogSpaceInBackground.func1()
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/metrics.go:173 +0x2a9
[2022-07-07T05:47:42.611Z] created by github.com/pingcap/tiflow/dm/relay.reportRelayLogSpaceInBackground
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/metrics.go:164 +0x111
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 109 [select]:
[2022-07-07T05:47:42.611Z] github.com/go-mysql-org/go-mysql/replication.(*BinlogStreamer).GetEvent(0xc000fb4fa0, {0x7f65fc8, 0xc000414900})
[2022-07-07T05:47:42.611Z] 	/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.4.1-0.20220221114137-89145541e0d4/replication/binlogstreamer.go:30 +0x18d
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/pkg/binlog/reader.(*TCPReader).GetEvent(0xc000ab2800, {0x7f65fc8, 0xc000414900})
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/pkg/binlog/reader/tcp.go:151 +0x33d
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/relay.(*upstreamReader).GetEvent(0xc0012357c0, {0x7f65fc8, 0xc000414900})
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/upstream_reader.go:135 +0x28e
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/relay.(*Relay).handleEvents(0xc001102420, {0x7f65fc8, 0xc000414900}, {0x7f5e4d0, 0xc0012357c0}, 0x2?)
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:573 +0x2a8
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/relay.(*Relay).process(0xc001102420, {0x7f65fc8?, 0xc000414900})
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:313 +0x195f
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/relay.(*Relay).Process(0xc001102420, {0x7f65fc8, 0xc000414900})
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:157 +0xba
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).run(0xc00067a680)
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:140 +0x1a2
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).Start.func1()
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:115 +0x85
[2022-07-07T05:47:42.611Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*realRelayHolder).Start
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/relay.go:113 +0xb7
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 243 [select]:
[2022-07-07T05:47:42.611Z] database/sql.(*DB).connectionOpener(0xc0004c1110, {0x7f65fc8, 0xc000414940})
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/database/sql/sql.go:1226 +0xf3
[2022-07-07T05:47:42.611Z] created by database/sql.OpenDB
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/database/sql/sql.go:794 +0x2f0
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 229 [select]:
[2022-07-07T05:47:42.611Z] github.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).Start(0xc000646b00)
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:172 +0x8e5
[2022-07-07T05:47:42.611Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*Server).getOrStartWorker
[2022-07-07T05:47:42.611Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:835 +0x93a
[2022-07-07T05:47:42.611Z] 
[2022-07-07T05:47:42.611Z] goroutine 313 [IO wait]:
[2022-07-07T05:47:42.611Z] internal/poll.runtime_pollWait(0x7f81f9d89658, 0x72)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/runtime/netpoll.go:302 +0x89
[2022-07-07T05:47:42.611Z] internal/poll.(*pollDesc).wait(0xc00067b418, 0xc000fb73c1?, 0x0)
[2022-07-07T05:47:42.611Z] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0xbd
[2022-07-07T05:47:42.611Z] internal/poll.(*pollDesc).waitRead(...)
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
[2022-07-07T05:47:42.612Z] internal/poll.(*FD).Read(0xc00067b400, {0xc000fb73c1, 0x1, 0x1})
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x415
[2022-07-07T05:47:42.612Z] net.(*netFD).Read(0xc00067b400, {0xc000fb73c1, 0x1, 0x1})
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/net/fd_posix.go:55 +0x51
[2022-07-07T05:47:42.612Z] net.(*conn).Read(0xc00129a6b0, {0xc000fb73c1, 0x1, 0x1})
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/net/net.go:183 +0xb1
[2022-07-07T05:47:42.612Z] github.com/soheilhy/cmux.(*bufferedReader).Read(0xc000bd7cf0, {0xc000fb73c1, 0x1, 0x1})
[2022-07-07T05:47:42.612Z] 	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/buffer.go:53 +0x2f8
[2022-07-07T05:47:42.612Z] github.com/soheilhy/cmux.(*MuxConn).Read(0xc000bd7ce0, {0xc000fb73c1, 0x1, 0x1})
[2022-07-07T05:47:42.612Z] 	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:297 +0x51
[2022-07-07T05:47:42.612Z] net/http.(*connReader).backgroundRead(0xc000fb73b0)
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/net/http/server.go:672 +0x72
[2022-07-07T05:47:42.612Z] created by net/http.(*connReader).startBackgroundRead
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/net/http/server.go:668 +0x19e
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 210 [select]:
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*Server).runBackgroundJob(0x0?, {0x7f65fc8, 0xc00055b0c0})
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/metrics.go:95 +0x1a5
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start.func1()
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:125 +0x5a
[2022-07-07T05:47:42.612Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:124 +0x849
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 207 [select]:
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/relay.(*Relay).doIntervalOps(0xc001102420, {0x7f65fc8, 0xc000414900})
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:844 +0x317
[2022-07-07T05:47:42.612Z] created by github.com/pingcap/tiflow/dm/relay.(*Relay).process
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/relay/relay.go:308 +0x136b
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 230 [select]:
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).run(0xc000d12360)
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:192 +0x845
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).Start.func1()
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:158 +0x85
[2022-07-07T05:47:42.612Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*realTaskStatusChecker).Start
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/task_checker.go:156 +0xb7
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 231 [select]:
[2022-07-07T05:47:42.612Z] database/sql.(*DB).connectionOpener(0xc0010a5a00, {0x7f65fc8, 0xc000d400c0})
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/database/sql/sql.go:1226 +0xf3
[2022-07-07T05:47:42.612Z] created by database/sql.OpenDB
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/database/sql/sql.go:794 +0x2f0
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 290 [select]:
[2022-07-07T05:47:42.612Z] github.com/soheilhy/cmux.muxListener.Accept({{0x7f636c0?, 0xc0012368d0?}, 0xc0006aa000?, 0xc0006a2060?})
[2022-07-07T05:47:42.612Z] 	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:262 +0xda
[2022-07-07T05:47:42.612Z] google.golang.org/grpc.(*Server).Serve(0xc000bfba40, {0x7f65040, 0xc0006b2000})
[2022-07-07T05:47:42.612Z] 	/go/pkg/mod/google.golang.org/grpc@v1.46.2/server.go:780 +0x5cb
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start.func4()
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:191 +0x99
[2022-07-07T05:47:42.612Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:190 +0x1a77
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 291 [select]:
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start.func5({0x7f65fc8, 0xc00055b0c0})
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:199 +0x131
[2022-07-07T05:47:42.612Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:197 +0x1c3b
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 292 [select]:
[2022-07-07T05:47:42.612Z] github.com/soheilhy/cmux.muxListener.Accept({{0x7f636c0?, 0xc0012368d0?}, 0xc0006aa120?, 0xc0006a20c0?})
[2022-07-07T05:47:42.612Z] 	/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:262 +0xda
[2022-07-07T05:47:42.612Z] net/http.(*Server).Serve(0xc001044000, {0x7f65040, 0xc0006b2020})
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/net/http/server.go:3039 +0x5a7
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.InitStatus({0x7f65040, 0xc0006b2020})
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/metrics.go:140 +0x21b
[2022-07-07T05:47:42.612Z] github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start.func6()
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:214 +0x74
[2022-07-07T05:47:42.612Z] created by github.com/pingcap/tiflow/dm/dm/worker.(*Server).Start
[2022-07-07T05:47:42.612Z] 	/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/server.go:212 +0x1d2b
[2022-07-07T05:47:42.612Z] 
[2022-07-07T05:47:42.612Z] goroutine 206 [IO wait]:
[2022-07-07T05:47:42.612Z] internal/poll.runtime_pollWait(0x7f81f9d89568, 0x72)
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/runtime/netpoll.go:302 +0x89
[2022-07-07T05:47:42.612Z] internal/poll.(*pollDesc).wait(0xc000ff4098, 0xc001190000?, 0x0)
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0xbd
[2022-07-07T05:47:42.612Z] internal/poll.(*pollDesc).waitRead(...)
[2022-07-07T05:47:42.612Z] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
[2022-07-07T05:47:42.612Z] internal/poll.(*FD).Read(0xc000ff4080, {0xc001190000, 0x10000, 0x10000})
[2022-07-07T05:47:42.613Z] 	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x415
[2022-07-07T05:47:42.613Z] net.(*netFD).Read(0xc000ff4080, {0xc001190000, 0x10000, 0x10000})
[2022-07-07T05:47:42.613Z] 	/usr/local/go/src/net/fd_posix.go:55 +0x51
[2022-07-07T05:47:42.613Z] net.(*conn).Read(0xc00056e210, {0xc001190000, 0x10000, 0x10000})
[2022-07-07T05:47:42.613Z] 	/usr/local/go/src/net/net.go:183 +0xb1
[2022-07-07T05:47:42.613Z] bufio.(*Reader).Read(0xc000fa0b40, {0xc0012358a8, 0x4, 0x4})
[2022-07-07T05:47:42.613Z] 	/usr/local/go/src/bufio/bufio.go:236 +0x4db
[2022-07-07T05:47:42.613Z] io.ReadAtLeast({0x7f3f080, 0xc000fa0b40}, {0xc0012358a8, 0x4, 0x4}, 0x4)
[2022-07-07T05:47:42.613Z] 	/usr/local/go/src/io/io.go:331 +0xde
[2022-07-07T05:47:42.613Z] io.ReadFull(...)
[2022-07-07T05:47:42.613Z] 	/usr/local/go/src/io/io.go:350
[2022-07-07T05:47:42.613Z] github.com/go-mysql-org/go-mysql/packet.(*Conn).ReadPacketTo(0xc001235860, {0x7f3f140?, 0xc0004b0fc0})
[2022-07-07T05:47:42.613Z] 	/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.4.1-0.20220221114137-89145541e0d4/packet/conn.go:149 +0x98
[2022-07-07T05:47:42.613Z] github.com/go-mysql-org/go-mysql/packet.(*Conn).ReadPacketReuseMem(0xc000e10f00?, {0x0, 0x0, 0x0})
[2022-07-07T05:47:42.613Z] 	/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.4.1-0.20220221114137-89145541e0d4/packet/conn.go:97 +0xd9
[2022-07-07T05:47:42.613Z] github.com/go-mysql-org/go-mysql/packet.(*Conn).ReadPacket(...)
[2022-07-07T05:47:42.613Z] 	/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.4.1-0.20220221114137-89145541e0d4/packet/conn.go:89
[2022-07-07T05:47:42.613Z] github.com/go-mysql-org/go-mysql/replication.(*BinlogSyncer).onStream(0xc000e10f00, 0xc000fb4fa0)
[2022-07-07T05:47:42.613Z] 	/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.4.1-0.20220221114137-89145541e0d4/replication/binlogsyncer.go:669 +0x11c
[2022-07-07T05:47:42.613Z] created by github.com/go-mysql-org/go-mysql/replication.(*BinlogSyncer).startDumpStream
[2022-07-07T05:47:42.613Z] 	/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.4.1-0.20220221114137-89145541e0d4/replication/binlogsyncer.go:370 +0x1b7
[2022-07-07T05:47:42.613Z] + echo ____________________________________
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

**Comment by lance6716** [comment]
dup with #5836
