### ISSUE TITLE
engine fake worker got stucked when creating etcd watcher

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#6245]
### What did you do?

run chaos test, ref: https://github.com/pingcap/tiflow/runs/7273256459?check_suite_focus=true

detail logs:
[chaos-base-logs.network-partition-dataflow.zip](https://github.com/pingcap/tiflow/files/9081572/chaos-base-logs.network-partition-dataflow.zip)
 

### What did you see instead?

```go
goroutine 511 [select, 6 minutes]:
go.etcd.io/etcd/client/v3.(*watcher).Watch(0xc002072d00, {0x406b468, 0xc0020720c0}, {0xc002032410?, 0x2?}, {0xc0020400f0?, 0x0?, 0x0?})
    go.etcd.io/etcd/client/v3@v3.5.2/watch.go:343 +0x545
github.com/pingcap/tiflow/engine/framework/fake.(*dummyWorker).createEtcdWatcher(0xc001fe3400, {0x406b468, 0xc0020720c0})
    github.com/pingcap/tiflow/engine/framework/fake/fake_worker.go:267 +0x356
github.com/pingcap/tiflow/engine/framework/fake.(*dummyWorker).bgRunEtcdWatcher.func1()
    github.com/pingcap/tiflow/engine/framework/fake/fake_worker.go:234 +0x3c
created by github.com/pingcap/tiflow/engine/framework/fake.(*dummyWorker).bgRunEtcdWatcher
    github.com/pingcap/tiflow/engine/framework/fake/fake_worker.go:233 +0x95
```

a new job master was created

```go
executor-2.log
10558:[2022/07/10 21:19:52.459 +00:00] [INFO] [fake_master.go:582] ["new fake master"] [config="{\"job-name\":\"fake-job-case\",\"worker-count\":8,\"target-tick\":10000000,\"etcd-watch-enable\":true,\"etcd-endpoints\":[\"metastore:12479\"],\"etcd-watch-prefix\":\"/fake-job/test/\",\"etcd-start-revision\":2,\"inject-error-interval\":0}"]
```

workers that are created with watcher successfully

```go
executor-1.log
10660:[2022/07/10 21:20:12.561 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/0] [revision=3767] [endpoints="[metastore:12479]"]
10662:[2022/07/10 21:20:12.579 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/7] [revision=3774] [endpoints="[metastore:12479]"]
10688:[2022/07/10 21:20:13.583 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/1] [revision=3768] [endpoints="[metastore:12479]"]
18518:[2022/07/10 21:25:18.476 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/6] [revision=3894] [endpoints="[metastore:12479]"]

executor-2.log
10880:[2022/07/10 21:20:16.592 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/5] [revision=3772] [endpoints="[metastore:12479]"]
11089:[2022/07/10 21:20:18.483 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/3] [revision=3770] [endpoints="[metastore:12479]"]

executor-3.log
37635:[2022/07/10 21:20:13.559 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/4] [revision=3771] [endpoints="[metastore:12479]"]
38817:[2022/07/10 21:22:45.477 +00:00] [INFO] [fake_worker.go:268] ["start to watch etcd"] [key=/fake-job/test/4] [revision=3892] [endpoints="[metastore:12479]"]
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

master@https://github.com/pingcap/tiflow/commit/e3d0d9d23b77c7884b70016ddbd8030ffeb95dfd

**Comment by amyangfei** [comment]
TiCDC could meet the same error here:
 https://github.com/pingcap/tiflow/blob/4d2f8fea1f3aa849c0c0b0fba65a79d2d0d18ca8/pkg/etcd/client.go#L257
