### ISSUE TITLE
Add version compatibility check between cdc server and cdc cli

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#629]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- start a cdc server with a latest version, such as `Release Version: v4.0.0-21-g965efef`
- create a changefeed with cdc cli, with version `Release Version: v4.0.0`

Because of a compatibility issue in changefeed info, cdc server panics

```
[2020/06/09 11:00:44.740 +08:00] [INFO] [owner.go:164] ["Find new changefeed"] [info="{\"sink-uri\":\"mysql://root@127.0.0.1:3306/\",\"opts\":{},\"create-time\":\"2020-06-09T11:00:44.28326856+08:00\",\"start-ts\":417247171517087745,\"target-ts\":0,\"admin-job-type\":0,\"sort-engine\":\"memory\",\"sort-dir\":\".\",\"config\":{\"case-sensitive\":true,\"filter\":{\"rules\":null,\"ignore-txn-start-ts\":null,\"ddl-white-list\":null},\"mounter\":{\"worker-num\":16},\"sink\":{\"dispatchers\":null},\"cyclic-replication\":{\"enable\":false,\"replica-id\":0,\"filter-replica-ids\":null,\"id-buckets\":0,\"sync-ddl\":false},\"scheduler\":null}}"] [id=eb88d739-8d22-41ef-9125-69b5baeaa961] ["checkpoint ts"=417247171517087745]
[2020/06/09 11:00:44.740 +08:00] [INFO] [store.go:68] ["new store"] [path="tikv://127.0.0.1:2379?disableGC=true"]
[2020/06/09 11:00:44.741 +08:00] [INFO] [client.go:149] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]
[2020/06/09 11:00:44.747 +08:00] [INFO] [base_client.go:242] ["[pd] switch leader"] [new-leader=http://127.0.0.1:2379] [old-leader=]
[2020/06/09 11:00:44.747 +08:00] [INFO] [base_client.go:92] ["[pd] init cluster id"] [cluster-id=6834699567180104901]
[2020/06/09 11:00:44.750 +08:00] [INFO] [store.go:74] ["new store with retry success"]
[2020/06/09 11:00:44.768 +08:00] [INFO] [client.go:249] ["get clusterID"] [id=6834699567180104901]
[2020/06/09 11:00:44.785 +08:00] [INFO] [mysql.go:341] ["Start mysql sink"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1f24431]

goroutine 223 [running]:
github.com/pingcap/ticdc/cdc.(*Owner).newChangeFeed(0xc00014b930, 0x2b32360, 0xc0005494c0, 0xc00071c9da, 0x24, 0xc000379c20, 0xc0004d3290, 0xc00039caf0, 0x5ca5c1781d00001, 0xc00063b730, ...)
        github.com/pingcap/ticdc@/cdc/owner.go:282 +0x1b51
github.com/pingcap/ticdc/cdc.(*Owner).loadChangeFeeds(0xc00014b930, 0x2b32360, 0xc00004d880, 0xc000723708, 0xc0007237b8)
        github.com/pingcap/ticdc@/cdc/owner.go:361 +0x3d2
github.com/pingcap/ticdc/cdc.(*Owner).run(0xc00014b930, 0x2b32360, 0xc00004d880, 0x0, 0x0)
        github.com/pingcap/ticdc@/cdc/owner.go:680 +0xa1
github.com/pingcap/ticdc/cdc.(*Owner).Run(0xc00014b930, 0x2b32360, 0xc00004d000, 0x1dcd6500, 0x0, 0x0)
        github.com/pingcap/ticdc@/cdc/owner.go:632 +0x2db
github.com/pingcap/ticdc/cdc.(*Server).campaignOwnerLoop(0xc000236100, 0x2b32360, 0xc00004d000, 0x0, 0x0)
        github.com/pingcap/ticdc@/cdc/server.go:196 +0x431
github.com/pingcap/ticdc/cdc.(*Server).run.func1(0xc00046b768, 0x0)
        github.com/pingcap/ticdc@/cdc/server.go:227 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000991410, 0xc0000c3780)
        golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

**Describe the feature you'd like:**

Use the same cdc binary will eliminate this problem. However there exists some unexpected scenario:
- users use different version binaries to start cdc server and create changefeed via cdc cli
- we could provide a ticdc-lib API to operate with cdc metadata, such as managing cdc from TiDB SQL command. The API version and cdc server version could be different.

**Describe alternatives you've considered:**

- Each cdc capture writes two fields in capture info: `version` and `min-version`, where `min-version` means the minimum compatibility version. Besides the owner writes a copy of `version` and `min-version` to a specific key.
- ticdc-lib API should have a version number, and each API request should check the `ticdc-lib` version is greater than the `min-version` of cdc cluster, if not the request will return an error.
- `cdc cli` also need to check the its version is greater than the `min-version` of cdc cluster, if not an error will be raised.

**Comment by overvenus** [comment]
I think this is a bug because we are using semver, we should guarantee patch releases are compatible.

**Comment by overvenus** [comment]
We has added version check in both cli and server.
