### ISSUE TITLE
test(engine): leak test fail for engine/pkg/etcdutil

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#6468]
### What did you do?

run unit test

### What did you expect to see?

all are passed

### What did you see instead?

```
PASS
coverage: 64.5% of statements
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 979 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 979 [select]:
net/http.(*persistConn).writeLoop(0xc00100a900)
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/transport.go:2392 +0x110
created by net/http.(*Transport).dialConn
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/transport.go:1751 +0x1bdc

 Goroutine 978 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 978 [IO wait]:
internal/poll.runtime_pollWait(0x10e864588, 0x72)
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0xc001092098, 0xc001042000?, 0x0)
	/opt/homebrew/Cellar/go/1.18/libexec/src/internal/poll/fd_poll_runtime.go:83 +0xc4
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.18/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001092080, {0xc001042000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.18/libexec/src/internal/poll/fd_unix.go:167 +0x2f0
net.(*netFD).Read(0xc001092080, {0xc001042000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/fd_posix.go:55 +0x4c
net.(*conn).Read(0xc0005fe0a0, {0xc001042000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/net.go:183 +0x8c
net/http.(*persistConn).Read(0xc00100a900, {0xc001042000, 0x1000, 0x1000})
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/transport.go:1929 +0xc8
bufio.(*Reader).fill(0xc001680d80)
	/opt/homebrew/Cellar/go/1.18/libexec/src/bufio/bufio.go:106 +0x21c
bufio.(*Reader).Peek(0xc001680d80, 0x1)
	/opt/homebrew/Cellar/go/1.18/libexec/src/bufio/bufio.go:144 +0xb4
net/http.(*persistConn).readLoop(0xc00100a900)
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/transport.go:2093 +0x21c
created by net/http.(*Transport).dialConn
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/transport.go:1750 +0x1b70

 Goroutine 967 in state sync.Cond.Wait, with sync.runtime_notifyListWait on top of the stack:
goroutine 967 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc0009e4490, 0x1)
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/sema.go:513 +0x170
sync.(*Cond).Wait(0xc0009e4480)
	/opt/homebrew/Cellar/go/1.18/libexec/src/sync/cond.go:56 +0xb4
net/http.(*connReader).abortPendingRead(0xc000f085a0)
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/server.go:720 +0x15c
net/http.(*response).finishRequest(0xc000fac700)
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/server.go:1633 +0xf4
net/http.(*conn).serve(0xc0004f0500, {0x103839658, 0xc000653350})
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/server.go:1972 +0x918
created by net/http.(*Server).Serve
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/server.go:3071 +0x640

 Goroutine 1110 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 1110 [IO wait]:
internal/poll.runtime_pollWait(0x10e81fbe0, 0x72)
	/opt/homebrew/Cellar/go/1.18/libexec/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0xc001092198, 0xc000f085b1?, 0x0)
	/opt/homebrew/Cellar/go/1.18/libexec/src/internal/poll/fd_poll_runtime.go:83 +0xc4
internal/poll.(*pollDesc).waitRead(...)
	/opt/homebrew/Cellar/go/1.18/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc001092180, {0xc000f085b1, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.18/libexec/src/internal/poll/fd_unix.go:167 +0x2f0
net.(*netFD).Read(0xc001092180, {0xc000f085b1, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/fd_posix.go:55 +0x4c
net.(*conn).Read(0xc0004a0060, {0xc000f085b1, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/net.go:183 +0x8c
go.etcd.io/etcd/client/pkg/v3/transport.timeoutConn.Read({{0x103847b68?, 0xc0004a0060?}, 0xc0afbb1eedf65b80?, 0x100dfc46c?}, {0xc000f085b1, 0x1, 0x1})
	/Users/maxshuang/go/pkg/mod/go.etcd.io/etcd/client/pkg/v3@v3.5.2/transport/timeout_conn.go:43 +0xa4
github.com/soheilhy/cmux.(*bufferedReader).Read(0xc000a040f0, {0xc000f085b1, 0x1, 0x1})
	/Users/maxshuang/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/buffer.go:53 +0x24c
github.com/soheilhy/cmux.(*MuxConn).Read(0xc000a040e0, {0xc000f085b1, 0x1, 0x1})
	/Users/maxshuang/go/pkg/mod/github.com/soheilhy/cmux@v0.1.5/cmux.go:297 +0x50
net/http.(*connReader).backgroundRead(0xc000f085a0)
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/server.go:672 +0x78
created by net/http.(*connReader).startBackgroundRead
	/opt/homebrew/Cellar/go/1.18/libexec/src/net/http/server.go:668 +0x14c
]
FAIL	github.com/pingcap/tiflow/engine/pkg/etcdutil	25.757s
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
master@659a9a0
```

**Comment by maxshuang** [comment]
this issue is no longer exists after https://github.com/pingcap/tiflow/pull/6389
