### ISSUE TITLE
doPostInit keeps failing because of target node id is not found when calling UpdateStatus

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#6524]
### What did you do?

run chaos case: https://github.com/CharlesCheung96/tiflow/runs/7571945777?check_suite_focus=true

detail logs:
[Uploading chaos-base-logs.pod-kill-dataflow.zip…]()
 

### What did you see instead?

- Looking into one executor

```go
➜  grep "UpdateStatus failed" chaos-executor-3.log
[2022/07/29 02:45:44.965 +00:00] [WARN] [writer.go:68] ["UpdateStatus failed"] [worker-id=cd47595b-d8df-49b2-9cf2-7d67ce409dce] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [master-node=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [master-epoch=6]
[2022/07/29 02:46:05.885 +00:00] [WARN] [writer.go:68] ["UpdateStatus failed"] [worker-id=0f9a0d35-7f73-4fe2-beb3-49875bb321fc] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [master-node=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [master-epoch=6]
[2022/07/29 02:46:26.890 +00:00] [WARN] [writer.go:68] ["UpdateStatus failed"] [worker-id=b9954764-0fa6-45c7-b881-114d8ab66c5b] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [master-node=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [master-epoch=6]
[2022/07/29 02:46:26.891 +00:00] [WARN] [writer.go:68] ["UpdateStatus failed"] [worker-id=8d9b2a12-6d4c-4fac-87e7-d8dbd2b4ae91] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [master-node=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [master-epoch=6]
[2022/07/29 02:46:47.884 +00:00] [WARN] [writer.go:68] ["UpdateStatus failed"] [worker-id=6ba0e558-1fff-42c7-8906-d930142df96f] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [master-node=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [master-epoch=6]
[2022/07/29 02:47:08.884 +00:00] [WARN] [writer.go:68] ["UpdateStatus failed"] [worker-id=b8f492e5-2723-4e70-87d0-61a9bac62e19] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [master-node=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [master-epoch=6]
```

```go
[2022/07/29 02:47:08.284 +00:00] [WARN] [message_router.go:124] ["failed to create client, no peer"] [target=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [stack="github.com/pingcap/tiflow/engine/pkg/p2p.(*messageSenderImpl).SendToNodeB\n\tgithub.com/pingcap/tiflow/engine/pkg/p2p/message_sender.go:52\ngithub.com/pingcap/tiflow/engine/framework/statusutil.(*Writer).sendStatusMessageWithRetry\n\tgithub.com/pingcap/tiflow/engine/framework/statusutil/writer.go:112\ngithub.com/pingcap/tiflow/engine/framework/statusutil.(*Writer).UpdateStatus\n\tgithub.com/pingcap/tiflow/engine/framework/statusutil/writer.go:85\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).doPostInit\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:325\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).Init\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:227\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).doRun\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:78\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:60\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:223"]
[2022/07/29 02:47:08.284 +00:00] [WARN] [writer.go:126] ["failed to send status to master. Retrying..."] [worker-id=b8f492e5-2723-4e70-87d0-61a9bac62e19] [master-id=7075adf8-17e5-4f60-a535-129c01dfd7f9] [status="{\"seq-id\":85,\"created-at\":\"2022-07-29T02:46:53.981Z\",\"updated-at\":\"2022-07-29T02:46:53.981Z\",\"project-id\":\"dfe_proj_default\",\"job-id\":\"7075adf8-17e5-4f60-a535-129c01dfd7f9\",\"id\":\"b8f492e5-2723-4e70-87d0-61a9bac62e19\",\"type\":7,\"code\":3,\"error-message\":\"\",\"ext-bytes\":null}"] [error="[DFLOW:ErrExecutorNotFoundForMessage]cannot find the executor for p2p messaging"] [errorVerbose="[DFLOW:ErrExecutorNotFoundForMessage]cannot find the executor for p2p messaging\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/engine/pkg/p2p.(*messageSenderImpl).SendToNodeB\n\tgithub.com/pingcap/tiflow/engine/pkg/p2p/message_sender.go:54\ngithub.com/pingcap/tiflow/engine/framework/statusutil.(*Writer).sendStatusMessageWithRetry\n\tgithub.com/pingcap/tiflow/engine/framework/statusutil/writer.go:112\ngithub.com/pingcap/tiflow/engine/framework/statusutil.(*Writer).UpdateStatus\n\tgithub.com/pingcap/tiflow/engine/framework/statusutil/writer.go:85\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).doPostInit\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:325\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseWorker).Init\n\tgithub.com/pingcap/tiflow/engine/framework/worker.go:227\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).doRun\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:78\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:60\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:223\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
```

The following error happens in each executor node, while `ebff1177-13ff-4a1c-b3c5-0b80f140aaac` is the node id of executor-0 before it restarts.

```go
["failed to create client, no peer"] [target=ebff1177-13ff-4a1c-b3c5-0b80f140aaac]
```

```go
[2022/07/29 02:44:52.963 +00:00] [INFO] [discovery_keepalive.go:94] ["add peer"] [uuid=ebff1177-13ff-4a1c-b3c5-0b80f140aaac] [exec="{\"type\":2,\"id\":\"ebff1177-13ff-4a1c-b3c5-0b80f140aaac\",\"addr\":\"chaos-executor-0.chaos-executor.default:10241\",\"cap\":100}"]
```

```go
37:[2022/07/29 02:37:31.937 +00:00] [INFO] [discovery_keepalive.go:94] ["add peer"] [uuid=ecaefac8-16ea-4973-be50-ce6c53e960ca] [exec="{\"type\":2,\"id\":\"ecaefac8-16ea-4973-be50-ce6c53e960ca\",\"addr\":\"chaos-executor-0.chaos-executor.default:10241\",\"cap\":100}"]
17167:[2022/07/29 02:40:14.349 +00:00] [INFO] [discovery_keepalive.go:94] ["add peer"] [uuid=ecaefac8-16ea-4973-be50-ce6c53e960ca] [exec="{\"type\":2,\"id\":\"ecaefac8-16ea-4973-be50-ce6c53e960ca\",\"addr\":\"chaos-executor-0.chaos-executor.default:10241\",\"cap\":100}"]
18590:[2022/07/29 02:44:52.267 +00:00] [INFO] [discovery_keepalive.go:94] ["add peer"] [uuid=ecaefac8-16ea-4973-be50-ce6c53e960ca] [exec="{\"type\":2,\"id\":\"ecaefac8-16ea-4973-be50-ce6c53e960ca\",\"addr\":\"chaos-executor-0.chaos-executor.default:10241\",\"cap\":100}"]
```

**So I suspected the record of this job in `master_meta_kv_data` table is not update to date.**

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

commit hash: 75904f2f15d10ef0af6571d5731c9fdaa08dc829

**Comment by amyangfei** [comment]
- etcd operation blocks at picking a gRPC transport, which leads to service discovery failure and missing new node id in p2p system.

```go
goroutine 236 [select]:
google.golang.org/grpc.(*pickerWrapper).pick(0xc000b7c480, {0x3e9fb10, 0xc001afe3c0}, 0x0, {{0x36e4231?, 0x0?}, {0x3e9fb10?, 0xc001afe3c0?}})
	google.golang.org/grpc@v1.46.2/picker_wrapper.go:103 +0x215
google.golang.org/grpc.(*ClientConn).getTransport(0xc001a8a2d0?, {0x3e9fb10?, 0xc001afe3c0?}, 0xc5?, {0x36e4231?, 0x36e4231?})
	google.golang.org/grpc@v1.46.2/clientconn.go:910 +0x35
google.golang.org/grpc.(*csAttempt).getTransport(0xc000e92630)
	google.golang.org/grpc@v1.46.2/stream.go:430 +0x48
google.golang.org/grpc.newClientStreamWithParams.func2(0xc000e92630)
	google.golang.org/grpc@v1.46.2/stream.go:315 +0x2b
google.golang.org/grpc.(*clientStream).withRetry(0xc001afa360, 0xc000c8df40, 0xc000d3d1d8)
	google.golang.org/grpc@v1.46.2/stream.go:709 +0xd3
google.golang.org/grpc.newClientStreamWithParams({0x3e9fb10, 0xc001afe2d0}, 0x6b6ad00, 0xc000294700, {0x36e4231, 0x16}, {0x0, 0x0, 0x0, 0x0, ...}, ...)
	google.golang.org/grpc@v1.46.2/stream.go:327 +0x9da
google.golang.org/grpc.newClientStream.func2({0x3e9fb10?, 0xc001afe2d0?}, 0xc001afe2d0?)
	google.golang.org/grpc@v1.46.2/stream.go:192 +0x9f
google.golang.org/grpc.newClientStream({0x3e9fb10, 0xc001afe2d0}, 0x6b6ad00, 0xc000294700, {0x36e4231, 0x16}, {0xc001af8500, 0x3, 0x4})
	google.golang.org/grpc@v1.46.2/stream.go:220 +0x4c2
google.golang.org/grpc.invoke({0x3e9fb10?, 0xc001afe2d0?}, {0x36e4231?, 0xba00000000?}, {0x3591d00, 0xc001a8a240}, {0x3530000, 0xc000b04140}, 0xb900000000?, {0xc001af8500, ...})
	google.golang.org/grpc@v1.46.2/call.go:66 +0x7d
go.etcd.io/etcd/client/v3.(*Client).unaryClientInterceptor.func1({0x3e9fa68?, 0xc000b95340?}, {0x36e4231, 0x16}, {0x3591d00, 0xc001a8a240}, {0x3530000, 0xc000b04140}, 0xc000294700, 0x3869c68, ...)
	go.etcd.io/etcd/client/v3@v3.5.2/retry_interceptor.go:58 +0x445
google.golang.org/grpc.(*ClientConn).Invoke(0x60?, {0x3e9fa68?, 0xc000b95340?}, {0x36e4231?, 0x6?}, {0x3591d00?, 0xc001a8a240?}, {0x3530000?, 0xc000b04140?}, {0xc000ebb9e0, ...})
	google.golang.org/grpc@v1.46.2/call.go:35 +0x223
go.etcd.io/etcd/api/v3/etcdserverpb.(*kVClient).Range(0xc00055d868, {0x3e9fa68, 0xc000b95340}, 0xc001a8a240?, {0xc000ebb9e0, 0x4, 0x6})
	go.etcd.io/etcd/api/v3@v3.5.2/etcdserverpb/rpc.pb.go:6460 +0xc9
go.etcd.io/etcd/client/v3.(*retryKVClient).Range(0xc000b11fe0, {0x3e9fa68, 0xc000b95340}, 0x84b860?, {0x6b6c060, 0x3, 0x3})
	go.etcd.io/etcd/client/v3@v3.5.2/retry.go:105 +0x127
go.etcd.io/etcd/client/v3.(*kv).Do(0xc00076aa20, {_, _}, {0x1, {0xc000d2ef30, 0x15, 0x18}, {0xc000d2ef48, 0x15, 0x15}, ...})
	go.etcd.io/etcd/client/v3@v3.5.2/kv.go:149 +0x1e8
go.etcd.io/etcd/client/v3.(*kv).Get(0xc00076aa20?, {0x3e9fa68, 0xc000b95340}, {0x36df62c?, 0x15?}, {0xc000443800?, 0x1?, 0x1?})
	go.etcd.io/etcd/client/v3@v3.5.2/kv.go:119 +0xdc
github.com/pingcap/tiflow/engine/pkg/srvdiscovery.(*EtcdSrvDiscovery).getSnapshot(0xc000e60840, {0x3e9fa68, 0xc000b95340})
	github.com/pingcap/tiflow/engine/pkg/srvdiscovery/etcd_impl.go:142 +0xde
github.com/pingcap/tiflow/engine/pkg/srvdiscovery.(*EtcdSrvDiscovery).delta(0xc000e60840, {0x3e9fa68?, 0xc000b95340?})
	github.com/pingcap/tiflow/engine/pkg/srvdiscovery/etcd_impl.go:118 +0x46
github.com/pingcap/tiflow/engine/pkg/srvdiscovery.(*EtcdSrvDiscovery).tickedWatch(0xc000e60840, {0x3e9fa68, 0xc000b95340}, 0x0?)
	github.com/pingcap/tiflow/engine/pkg/srvdiscovery/etcd_impl.go:98 +0x10b
created by github.com/pingcap/tiflow/engine/pkg/srvdiscovery.(*EtcdSrvDiscovery).Watch
	github.com/pingcap/tiflow/engine/pkg/srvdiscovery/etcd_impl.go:73 +0x138
```

- It was caused by we enable `AutoSync` in etcd client 

https://github.com/pingcap/tiflow/blob/bb5ba3c9535ceae5d8db36eae5df9e3fa3d0f2e7/engine/executor/server/metastore.go#L115

- And the `advertise-addr` of etcd cluster was configured with wrong value

https://github.com/CharlesCheung96/tiflow/blob/6d22cc23794e5b19c45a4c538227250bc2cc8c92/engine/deployments/helm/tiflow/templates/metastore-etcd.yaml#L65
