### ISSUE TITLE
DM may stuck at syncer initialization

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#6898]
### What did you do?

https://asktug.com/t/topic/903490/8?u=lance6716

```
goroutine 358 [select]:
github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob(0xc0111c3780, {0x3974878?, 0xc011ec1200?}, 0xc0007d6d80)
	github.com/pingcap/tidb@v1.1.0-beta.0.20220528045048-5495dc6c4360/ddl/ddl.go:699 +0x752
github.com/pingcap/tidb/ddl.(*ddl).BatchCreateTableWithInfo(0x2bdda00?, {0x3974878, 0xc011ec1200}, {{0xc00057f980?, 0x1008ba698?}, {0xc00057f980?, 0x4?}}, {0xc012181800, 0x95, 0x100}, ...)
	github.com/pingcap/tidb@v1.1.0-beta.0.20220528045048-5495dc6c4360/ddl/ddl_api.go:2451 +0x706
github.com/pingcap/tiflow/dm/pkg/schema.(*Tracker).BatchCreateTableIfNotExist(0xc000f1c7e0, 0x3253c7d?)
	github.com/pingcap/tiflow/dm/pkg/schema/tracker.go:458 +0x21e
github.com/pingcap/tiflow/dm/syncer.(*RemoteCheckPoint).LoadIntoSchemaTracker(0xc0010da4e0, {0xc000dffe40?, 0xc00127f538?}, 0x5?)
	github.com/pingcap/tiflow/dm/syncer/checkpoint.go:1104 +0x1de
github.com/pingcap/tiflow/dm/syncer.(*Syncer).Run(0xc000475680, {0x391a0b8?, 0xc000dffe40?})
	github.com/pingcap/tiflow/dm/syncer/syncer.go:1703 +0xeb1
github.com/pingcap/tiflow/dm/syncer.(*Syncer).Process(0xc000475680, {0x391a0b8, 0xc000dffd80}, 0xc000175320?)
	github.com/pingcap/tiflow/dm/syncer/syncer.go:702 +0x392
created by github.com/pingcap/tiflow/dm/dm/worker.(*SubTask).run
	github.com/pingcap/tiflow/dm/dm/worker/subtask.go:260 +0x56c
```

### What did you expect to see?

the internal call of `BatchCreateTableWithInfo` should not stuck

### What did you see instead?

see above

### Versions of the cluster

v6.1.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by lance6716** [comment]
this should be solved by https://github.com/pingcap/tiflow/issues/5334 in v6.3.0

**Comment by lance6716** [comment]
the user says it has 800 tables in one task, and the goroutine stack shows it is waiting at 

https://github.com/pingcap/tidb/blob/b99aebee3110e539bec53bbd8838fa554ad4e653/ddl/ddl.go#L490-L495

800*0.1s = 80s
