### ISSUE TITLE
master(engine): unexpected core dump for server master 

### ISSUE THREAD

**Issue by maxshuang** [pingcap/tiflow#6964]
### What did you do?

run a 1 servermaster 1 executor tiflow cluster 

### What did you expect to see?

run normally

### What did you see instead?

server master core dump
```
docker container logs 3c1f3f2a5ab2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c17dfc]

goroutine 13341 [running]:
github.com/pingcap/tiflow/engine/pkg/notifier.(*Receiver[...]).Close(0x400199e090?)
	github.com/pingcap/tiflow/engine/pkg/notifier/notifier.go:65 +0x1c
github.com/pingcap/tiflow/engine/servermaster/serverutil.WatchExecutors({0x37aab80, 0x4001a5dd00}, {0xffff6fe33d78, 0x400032e380}, {0x37a8030, 0x4001a51fb0})
	github.com/pingcap/tiflow/engine/servermaster/serverutil/watch_executors.go:65 +0x3c4
github.com/pingcap/tiflow/engine/servermaster.(*Server).runLeaderService.func13()
	github.com/pingcap/tiflow/engine/servermaster/server.go:940 +0x9c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa8
```

log:
```
[2022/09/04 14:31:43.414 +00:00] [WARN] [discovery_keepalive.go:104] ["metastore session is done"] [executor-id=server-master-990e160a-c73b-4b4e-a0f8-d772d270ed53]
[2022/09/04 14:31:43.414 +00:00] [INFO] [gc_runner.go:67] ["default gc runner exited"]
[2022/09/04 14:31:43.414 +00:00] [WARN] [watch_executors.go:60] ["WatchExecutors took too long"] [duration=1m0.506749028s] [snap=null]
[2022/09/04 14:31:43.414 +00:00] [INFO] [watch_executors.go:52] ["WatchExecutors exited"] [error="watch executors: [DFLOW:ErrMasterSessionDone]master session is done"]
```
[server-master-0.log](https://github.com/pingcap/tiflow/files/9486542/server-master-0.log)

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
master@12ff137
```

**Comment by maxshuang** [comment]
@gozssky can you take a look at it?
