### ISSUE TITLE
cdc close mq produce panic

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#7121]
### What did you do?

use sink v1, do nothing special

### What did you expect to see?

works normally.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x29d8cce]

goroutine 1416 [running]:
github.com/pingcap/tiflow/cdc/sink/mq.(*mqSink).Close(0x0, {0x21?, 0xc02484ac80?})
        github.com/pingcap/tiflow/cdc/sink/mq/mq.go:322 +0x2e
github.com/pingcap/tiflow/cdc/processor.(*processor).Close(0xc00753f200)
        github.com/pingcap/tiflow/cdc/processor/processor.go:1065 +0xdf5
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).closeProcessor(0xc0007f58c0, {{0xc000772892?, 0xc00c12f128?}, {0xc0007728aa?, 0x4234dff63?}})
        github.com/pingcap/tiflow/cdc/processor/manager.go:155 +0xcb
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc0007f58c0, {0x7ff3097890d8?, 0xc0006248a0}, {0x3ba0600?, 0xc002080540})
        github.com/pingcap/tiflow/cdc/processor/manager.go:129 +0x456
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc002d18780, {0x7ff3097890d8, 0xc0006248a0}, 0xc0005b3b30, 0x5f5e100, {0x34341d7, 0x9})
        github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:266 +0xe63
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc0008930e0, {0x3bd40a0?, 0xc0006248a0}, {0x7ff309a96460, 0xc0007f58c0}, {0x3ba0600, 0xc002080540}, 0x43b892?, {0x34341d7, 0x9})
        github.com/pingcap/tiflow/cdc/capture/capture.go:490 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4()
        github.com/pingcap/tiflow/cdc/capture/capture.go:333 +0x28f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa5
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by 3AceShowHand** [comment]
```
[2022/09/19 21:54:54.540 +08:00] [INFO] [helper.go:50] ["init log"] [file=/root/tidb-deploy/cdc-8300/log/cdc.log] [level=info]
[2022/09/19 21:54:54.541 +08:00] [INFO] [version.go:47] ["Welcome to Change Data Capture (CDC)"] [release-version=v6.3.0-master-dirty] [git-hash=b56da0501f79db512e7241534ccecc28f71fe543] [git-branch=sarama-bump-1.36.0] [utc-build-time="2022-09-19 13:53:43"] [go-version="go version go1.18 linux/amd64"] [failpoint-build=false]
[2022/09/19 21:54:54.541 +08:00] [INFO] [server.go:119] ["CDC server created"] [pd="[http://lingjin-1.jinling.tispace:2379,http://lingjin-0.jinling.tispace:2379]"] [config="{\"addr\":\"0.0.0.0:8300\",\"advertise-addr\":\"lingjin-3.jinling.tispace:8300\",\"log-file\":\"/root/tidb-deploy/cdc-8300/log/cdc.log\",\"log-level\":\"info\",\"log\":{\"file\":{\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"error-output\":\"stderr\"},\"data-dir\":\"/root/tidb-data/cdc-8300\",\"gc-ttl\":86400,\"tz\":\"System\",\"capture-session-ttl\":10,\"owner-flush-interval\":200000000,\"processor-flush-interval\":100000000,\"sorter\":{\"num-concurrent-worker\":4,\"chunk-size-limit\":134217728,\"max-memory-percentage\":30,\"max-memory-consumption\":17179869184,\"num-workerpool-goroutine\":16,\"sort-dir\":\"/tmp/sorter\"},\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cert-allowed-cn\":null},\"per-table-memory-quota\":10485760,\"kv-client\":{\"worker-concurrent\":8,\"worker-pool-size\":0,\"region-scan-limit\":40,\"region-retry-duration\":60000000000},\"debug\":{\"table-actor\":{\"event-batch-size\":32},\"enable-db-sorter\":true,\"db\":{\"count\":8,\"concurrency\":128,\"max-open-files\":10000,\"block-size\":65536,\"writer-buffer-size\":8388608,\"compression\":\"snappy\",\"write-l0-pause-trigger\":2147483647,\"compaction-l0-trigger\":160,\"compaction-deletion-threshold\":10485760,\"compaction-period\":1800,\"iterator-max-alive-duration\":10000,\"iterator-slow-read-duration\":256},\"enable-new-scheduler\":true,\"messages\":{\"client-max-batch-interval\":10000000,\"client-max-batch-size\":8388608,\"client-max-batch-count\":128,\"client-retry-rate-limit\":1,\"server-max-pending-message-count\":102400,\"server-ack-interval\":100000000,\"server-worker-pool-size\":4},\"enable-scheduler-v3\":true,\"scheduler\":{\"heartbeat-tick\":2,\"max-task-concurrency\":10,\"check-balance-interval\":60000000000,\"add-table-batch-size\":50},\"enable-new-sink\":false},\"cluster-id\":\"default\"}"]
[2022/09/19 21:54:54.547 +08:00] [INFO] [server.go:415] ["/root/tidb-data/cdc-8300 is set as data-dir (487GB available), sort-dir=/root/tidb-data/cdc-8300/tmp/sorter. It is recommended that the disk for data-dir at least have 500GB available space"]
[2022/09/19 21:54:54.575 +08:00] [INFO] [server.go:264] ["http server is running"] [addr=0.0.0.0:8300]
[2022/09/19 21:54:54.603 +08:00] [INFO] [api_client.go:123] ["Succeed to add meta region label to PD"]
[2022/09/19 21:54:54.603 +08:00] [INFO] [upstream.go:210] ["upstream initialize successfully"] [upstreamID=7133877136889696851]
[2022/09/19 21:54:54.603 +08:00] [INFO] [manager.go:97] ["default upstream is added"] [id=7133877136889696851]
[2022/09/19 21:54:54.604 +08:00] [INFO] [capture.go:236] ["capture initialized"] [capture="{\"id\":\"fa7bd620-781f-4717-8f95-a2a2946d083b\",\"address\":\"lingjin-3.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:54:54.608 +08:00] [INFO] [reactor_state.go:86] ["remote capture online"] [info="{\"id\":\"a30f8c1d-6746-49b6-a8d3-0cc1083ba37e\",\"address\":\"lingjin-4.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:54:54.608 +08:00] [INFO] [reactor_state.go:86] ["remote capture online"] [info="{\"id\":\"fa7bd620-781f-4717-8f95-a2a2946d083b\",\"address\":\"lingjin-3.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:54:54.609 +08:00] [INFO] [reactor_state.go:122] ["new upstream is add"] [upstream=7133877136889696851] [info="{\"id\":7133877136889696851,\"pd-endpoints\":\"http://lingjin-1.jinling.tispace:2379,http://lingjin-9.jinling.tispace:2379,http://lingjin-0.jinling.tispace:2379\",\"key-path\":\"\",\"cert-path\":\"\",\"ca-path\":\"\",\"cert-allowed-cn\":null}"]
[2022/09/19 21:54:54.813 +08:00] [INFO] [middleware.go:48] [/api/v1/health] [status=500] [method=GET] [path=/api/v1/health] [query=] [ip=10.244.4.132] [user-agent=Go-http-client/1.1] [client-version=] [] [duration=45.421793ms]
[2022/09/19 21:54:55.132 +08:00] [INFO] [processor.go:671] ["Try to create sinkV1"]
[2022/09/19 21:54:55.132 +08:00] [WARN] [sink.go:162] ["protocol is specified in both sink URI and config filethe value in sink URI will be usedprotocol in sink URI:canal-json, protocol in config file:canal-json"]
[2022/09/19 21:54:55.132 +08:00] [INFO] [sink.go:183] ["succeed to parse parameter from sink uri"] [protocol=canal-json] [txnAtomicity=none]
[2022/09/19 21:54:55.146 +08:00] [WARN] [kafka.go:461] ["broker's `message.max.bytes` less than the `max-message-bytes`,use broker's `message.max.bytes` to initialize the Kafka producer"] [message.max.bytes=1048588] [max-message-bytes=10485760]
[2022/09/19 21:54:55.151 +08:00] [INFO] [kafka_manager.go:219] ["Kafka admin client list topics success"] [duration=539.743µs]
[2022/09/19 21:54:55.152 +08:00] [INFO] [kafka_manager.go:151] ["Kafka admin client describe topics success"] [duration=340.876µs]
[2022/09/19 21:54:55.153 +08:00] [ERROR] [kafka_manager.go:284] ["Kafka admin client create the topic failed"] [topic=canal-json-kafka-test] [partitionNumber=3] [replicationFactor=2] [error="kafka server: Replication-factor is invalid - Replication factor: 2 larger than available brokers: 1."] [duration=811.771µs]
[2022/09/19 21:54:55.153 +08:00] [INFO] [processor.go:687] ["processor creates sink failed"] [namespace=default] [changefeed=canal-json-kafka-test] [duration=20.854941ms]
[2022/09/19 21:54:55.153 +08:00] [ERROR] [processor.go:543] ["run processor failed"] [capture=fa7bd620-781f-4717-8f95-a2a2946d083b] [namespace=default] [changefeed=canal-json-kafka-test] [error="[CDC:ErrKafkaCreateTopic]kafka create topic failed: [CDC:ErrKafkaNewSaramaProducer]new sarama producer: kafka server: Replication-factor is invalid - Replication factor: 2 larger than available brokers: 1."] [errorVerbose="[CDC:ErrKafkaCreateTopic]kafka create topic failed: [CDC:ErrKafkaNewSaramaProducer]new sarama producer: kafka server: Replication-factor is invalid - Replication factor: 2 larger than available brokers: 1.\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tiflow/pkg/errors.WrapError\n\tgithub.com/pingcap/tiflow/pkg/errors/helper.go:32\ngithub.com/pingcap/tiflow/cdc/sink/mq.NewKafkaSaramaSink\n\tgithub.com/pingcap/tiflow/cdc/sink/mq/mq.go:447\ngithub.com/pingcap/tiflow/cdc/sink.init.0.func3\n\tgithub.com/pingcap/tiflow/cdc/sink/sink.go:126\ngithub.com/pingcap/tiflow/cdc/sink.New\n\tgithub.com/pingcap/tiflow/cdc/sink/sink.go:146\ngithub.com/pingcap/tiflow/cdc/processor.(*processor).lazyInitImpl\n\tgithub.com/pingcap/tiflow/cdc/processor/processor.go:672\ngithub.com/pingcap/tiflow/cdc/processor.(*processor).tick\n\tgithub.com/pingcap/tiflow/cdc/processor/processor.go:562\ngithub.com/pingcap/tiflow/cdc/processor.(*processor).Tick\n\tgithub.com/pingcap/tiflow/cdc/processor/processor.go:496\ngithub.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick\n\tgithub.com/pingcap/tiflow/cdc/processor/manager.go:128\ngithub.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run\n\tgithub.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:266\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:491\ngithub.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4\n\tgithub.com/pingcap/tiflow/cdc/capture/capture.go:334\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75\nruntime.goexit\n\truntime/asm_amd64.s:1571"]
[2022/09/19 21:54:55.153 +08:00] [INFO] [processor.go:1037] ["processor closing ..."] [namespace=default] [changefeed=canal-json-kafka-test]
[2022/09/19 21:54:55.233 +08:00] [INFO] [processor.go:1061] ["processor try to close the sinkV1"] [namespace=default] [changefeed=canal-json-kafka-test]
[2022/09/19 21:54:55.233 +08:00] [INFO] [client.go:235] ["WatchWithChan exited"] [role=processor]
[2022/09/19 21:55:00.252 +08:00] [INFO] [helper.go:50] ["init log"] [file=/root/tidb-deploy/cdc-8300/log/cdc.log] [level=info]
[2022/09/19 21:55:00.253 +08:00] [INFO] [version.go:47] ["Welcome to Change Data Capture (CDC)"] [release-version=v6.3.0-master-dirty] [git-hash=b56da0501f79db512e7241534ccecc28f71fe543] [git-branch=sarama-bump-1.36.0] [utc-build-time="2022-09-19 13:53:43"] [go-version="go version go1.18 linux/amd64"] [failpoint-build=false]
[2022/09/19 21:55:00.253 +08:00] [INFO] [server.go:119] ["CDC server created"] [pd="[http://lingjin-1.jinling.tispace:2379,http://lingjin-0.jinling.tispace:2379]"] [config="{\"addr\":\"0.0.0.0:8300\",\"advertise-addr\":\"lingjin-3.jinling.tispace:8300\",\"log-file\":\"/root/tidb-deploy/cdc-8300/log/cdc.log\",\"log-level\":\"info\",\"log\":{\"file\":{\"max-size\":300,\"max-days\":0,\"max-backups\":0},\"error-output\":\"stderr\"},\"data-dir\":\"/root/tidb-data/cdc-8300\",\"gc-ttl\":86400,\"tz\":\"System\",\"capture-session-ttl\":10,\"owner-flush-interval\":200000000,\"processor-flush-interval\":100000000,\"sorter\":{\"num-concurrent-worker\":4,\"chunk-size-limit\":134217728,\"max-memory-percentage\":30,\"max-memory-consumption\":17179869184,\"num-workerpool-goroutine\":16,\"sort-dir\":\"/tmp/sorter\"},\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cert-allowed-cn\":null},\"per-table-memory-quota\":10485760,\"kv-client\":{\"worker-concurrent\":8,\"worker-pool-size\":0,\"region-scan-limit\":40,\"region-retry-duration\":60000000000},\"debug\":{\"table-actor\":{\"event-batch-size\":32},\"enable-db-sorter\":true,\"db\":{\"count\":8,\"concurrency\":128,\"max-open-files\":10000,\"block-size\":65536,\"writer-buffer-size\":8388608,\"compression\":\"snappy\",\"write-l0-pause-trigger\":2147483647,\"compaction-l0-trigger\":160,\"compaction-deletion-threshold\":10485760,\"compaction-period\":1800,\"iterator-max-alive-duration\":10000,\"iterator-slow-read-duration\":256},\"enable-new-scheduler\":true,\"messages\":{\"client-max-batch-interval\":10000000,\"client-max-batch-size\":8388608,\"client-max-batch-count\":128,\"client-retry-rate-limit\":1,\"server-max-pending-message-count\":102400,\"server-ack-interval\":100000000,\"server-worker-pool-size\":4},\"enable-scheduler-v3\":true,\"scheduler\":{\"heartbeat-tick\":2,\"max-task-concurrency\":10,\"check-balance-interval\":60000000000,\"add-table-batch-size\":50},\"enable-new-sink\":false},\"cluster-id\":\"default\"}"]
[2022/09/19 21:55:00.259 +08:00] [INFO] [server.go:415] ["/root/tidb-data/cdc-8300 is set as data-dir (487GB available), sort-dir=/root/tidb-data/cdc-8300/tmp/sorter. It is recommended that the disk for data-dir at least have 500GB available space"]
[2022/09/19 21:55:00.285 +08:00] [INFO] [server.go:264] ["http server is running"] [addr=0.0.0.0:8300]
[2022/09/19 21:55:00.312 +08:00] [INFO] [api_client.go:123] ["Succeed to add meta region label to PD"]
[2022/09/19 21:55:00.312 +08:00] [INFO] [upstream.go:210] ["upstream initialize successfully"] [upstreamID=7133877136889696851]
[2022/09/19 21:55:00.312 +08:00] [INFO] [manager.go:97] ["default upstream is added"] [id=7133877136889696851]
[2022/09/19 21:55:00.313 +08:00] [INFO] [capture.go:236] ["capture initialized"] [capture="{\"id\":\"e2d204a7-4eb5-4ed0-939d-d8661d06d77d\",\"address\":\"lingjin-3.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:55:00.317 +08:00] [INFO] [reactor_state.go:86] ["remote capture online"] [info="{\"id\":\"a30f8c1d-6746-49b6-a8d3-0cc1083ba37e\",\"address\":\"lingjin-4.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:55:00.317 +08:00] [INFO] [reactor_state.go:86] ["remote capture online"] [info="{\"id\":\"e2d204a7-4eb5-4ed0-939d-d8661d06d77d\",\"address\":\"lingjin-3.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:55:00.317 +08:00] [INFO] [reactor_state.go:86] ["remote capture online"] [info="{\"id\":\"fa7bd620-781f-4717-8f95-a2a2946d083b\",\"address\":\"lingjin-3.jinling.tispace:8300\",\"version\":\"v6.3.0-master-dirty\"}"]
[2022/09/19 21:55:00.318 +08:00] [INFO] [reactor_state.go:122] ["new upstream is add"] [upstream=7133877136889696851] [info="{\"id\":7133877136889696851,\"pd-endpoints\":\"http://lingjin-1.jinling.tispace:2379,http://lingjin-9.jinling.tispace:2379,http://lingjin-0.jinling.tispace:2379\",\"key-path\":\"\",\"cert-path\":\"\",\"ca-path\":\"\",\"cert-allowed-cn\":null}"]
[2022/09/19 21:55:00.892 +08:00] [INFO] [processor.go:671] ["Try to create sinkV1"]
```
