### ISSUE TITLE
kv client panic since commit ts less than the resolved ts

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#7549]
### What did you do?

`tiup cluster patch` a one node cdc cluster.

### What did you expect to see?

works normally.

### What did you see instead?

```
[2022/11/08 16:16:55.502 +08:00] [PANIC] [global.go:54] ["The CommitTs must be greater than the resolvedTs"] [EventType=COMMIT] [CommitTs=437228773901860877] [resolvedTs=437228774596542468] [regionID=48385] [stack="github.com/pingcap/log.Panic\n\tgithub.com/pingcap/log@v1.1.1-0.20221015072633-39906604fb81/global.go:54\ngithub.com/pingcap/tiflow/cdc/kv.(*regionWorker).handleEventEntry\n\tgithub.com/pingcap/tiflow/cdc/kv/region_worker.go:679\ngithub.com/pingcap/tiflow/cdc/kv.(*regionWorker).processEvent\n\tgithub.com/pingcap/tiflow/cdc/kv/region_worker.go:362\ngithub.com/pingcap/tiflow/cdc/kv.(*regionWorker).eventHandler\n\tgithub.com/pingcap/tiflow/cdc/kv/region_worker.go:508\ngithub.com/pingcap/tiflow/cdc/kv.(*regionWorker).run.func4\n\tgithub.com/pingcap/tiflow/cdc/kv/region_worker.go:593\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75"]
```
```
panic: The CommitTs must be greater than the resolvedTs

goroutine 1665 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x4?, 0x4?, {0x0?, 0x0?, 0xc005c22440?})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0043c08f0, {0xc004db3b00, 0x4, 0x4})
	go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc007ce3a00?, {0x37d44b0?, 0x40dca7?}, {0xc004db3b00, 0x4, 0x4})
	go.uber.org/zap@v1.23.0/logger.go:251 +0x59
github.com/pingcap/log.Panic({0x37d44b0, 0x30}, {0xc004db3b00, 0x4, 0x4})
	github.com/pingcap/log@v1.1.1-0.20221015072633-39906604fb81/global.go:54 +0x50
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).handleEventEntry(0xc004602630, {0x3fd2da8, 0xc0040febc0}, 0xc005dc5d60?, 0xc005191710)
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:679 +0x1149
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).processEvent(0xc004602630, {0x3fd2da8, 0xc0040febc0}, 0xc007413770)
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:362 +0x4d7
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).eventHandler(0xc004602630, {0x3fd2da8, 0xc0040febc0})
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:508 +0x58d
github.com/pingcap/tiflow/cdc/kv.(*regionWorker).run.func4()
	github.com/pingcap/tiflow/cdc/kv/region_worker.go:593 +0x2e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa5
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
Release Version:   6.3.0
Edition:           Community
Git Commit Hash:   f9ae84f772c522dea7d57dceedba801db3a2103c
Git Commit Branch: heads/refs/tags/v6.3.0
UTC Build Time:    2022-09-27 10:37:15
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by 3AceShowHand** [comment]
tikv log: 
```
[2022/11/08 16:15:27.137 +08:00] [INFO] [delegate.rs:905] ["stop observing"] [failed=false] [region_id=48385]
[2022/11/08 16:16:54.943 +08:00] [INFO] [endpoint.rs:760] ["cdc register region"] [downstream_id=DownstreamId(159360)] [observe_id=ObserveId(183284)] [req_id=3439] [conn_id=ConnId(1927)] [region_id=48385]
[2022/11/08 16:16:54.980 +08:00] [INFO] [endpoint.rs:1334] ["cdc downstream starts to initialize"] [downstream_id=DownstreamId(159360)] [region_id=48385]
[2022/11/08 16:16:54.980 +08:00] [INFO] [initializer.rs:530] ["cdc incremental scan uses ts filter: true"] [tables=7] [filtered_versions=40961] [mvcc_versions=40961] [hint_min_ts=437228774596542468] [region_id=48385]
[2022/11/08 16:16:54.983 +08:00] [INFO] [initializer.rs:294] ["cdc async incremental scan finished"] [takes=3ms] [downstream_id=DownstreamId(159360)] [conn_id=ConnId(1927)] [region_id=48385]
[2022/11/08 16:16:54.984 +08:00] [INFO] [initializer.rs:453] ["cdc resolver initialized and schedule resolver ready"] [observe_id=ObserveId(183284)] [lock_count=2] [resolved_ts=0] [downstream_id=DownstreamId(159360)] [conn_id=ConnId(1927)] [region_id=48385]
[2022/11/08 16:16:54.984 +08:00] [INFO] [delegate.rs:396] ["cdc region is ready"] [region_id=48385]
[2022/11/08 16:16:55.536 +08:00] [INFO] [delegate.rs:905] ["stop observing"] [failed=false] [region_id=48385]
[2022/11/08 16:17:12.892 +08:00] [INFO] [endpoint.rs:760] ["cdc register region"] [downstream_id=DownstreamId(160842)] [observe_id=ObserveId(184770)] [req_id=2513] [conn_id=ConnId(1935)] [region_id=48385]
[2022/11/08 16:17:12.908 +08:00] [INFO] [endpoint.rs:1334] ["cdc downstream starts to initialize"] [downstream_id=DownstreamId(160842)] [region_id=48385]
[2022/11/08 16:17:12.909 +08:00] [INFO] [initializer.rs:530] ["cdc incremental scan uses ts filter: true"] [tables=8] [filtered_versions=40961] [mvcc_versions=40961] [hint_min_ts=437228774596542468] [region_id=48385]
[2022/11/08 16:17:12.911 +08:00] [INFO] [initializer.rs:294] ["cdc async incremental scan finished"] [takes=2ms] [downstream_id=DownstreamId(160842)] [conn_id=ConnId(1935)] [region_id=48385]
[2022/11/08 16:17:12.911 +08:00] [INFO] [initializer.rs:453] ["cdc resolver initialized and schedule resolver ready"] [observe_id=ObserveId(184770)] [lock_count=1] [resolved_ts=0] [downstream_id=DownstreamId(160842)] [conn_id=ConnId(1935)] [region_id=48385]
[2022/11/08 16:17:12.911 +08:00] [INFO] [delegate.rs:396] ["cdc region is ready"] [region_id=48385]
[2022/11/08 16:18:48.800 +08:00] [INFO] [delegate.rs:905] ["stop observing"] [failed=false] [region_id=48385]
[2022/11/08 16:32:05.799 +08:00] [INFO] [endpoint.rs:760] ["cdc register region"] [downstream_id=DownstreamId(165696)] [observe_id=ObserveId(189705)] [req_id=16646] [conn_id=ConnId(1944)] [region_id=48385]
[2022/11/08 16:32:06.418 +08:00] [INFO] [endpoint.rs:1334] ["cdc downstream starts to initialize"] [downstream_id=DownstreamId(165696)] [region_id=48385]
[2022/11/08 16:32:06.418 +08:00] [INFO] [initializer.rs:530] ["cdc incremental scan uses ts filter: true"] [tables=4] [filtered_versions=1] [mvcc_versions=1] [hint_min_ts=437228774596542468] [region_id=48385]
[2022/11/08 16:32:06.459 +08:00] [INFO] [initializer.rs:294] ["cdc async incremental scan finished"] [takes=41ms] [downstream_id=DownstreamId(165696)] [conn_id=ConnId(1944)] [region_id=48385]
[2022/11/08 16:32:06.459 +08:00] [INFO] [initializer.rs:453] ["cdc resolver initialized and schedule resolver ready"] [observe_id=ObserveId(189705)] [lock_count=1] [resolved_ts=0] [downstream_id=DownstreamId(165696)] [conn_id=ConnId(1944)] [region_id=48385]
[2022/11/08 16:32:06.459 +08:00] [INFO] [delegate.rs:396] ["cdc region is ready"] [region_id=48385]
[2022/11/08 16:34:44.219 +08:00] [INFO] [split_check.rs:590] ["update approximate size and keys with accurate value"] [bucket_size=0] [bucket_count=0] [keys=148385] [size=147489950] [region_id=66081]
[2022/11/08 18:11:23.796 +08:00] [INFO] [raft.rs:1299] ["broadcasting vote request"] [to="[2881, 2883]"] [log_index=483850] [log_term=9] [term=10] [type=MsgRequestVote] [raft_id=2882] [region_id=2880]
[2022/11/08 18:11:23.797 +08:00] [INFO] [endpoint.rs:247] ["Resolver initialized"] [pending_data_index=0] [snapshot_index=483851] [observe_id=ObserveId(197198)] [region=2880]
[2022/11/08 19:43:18.935 +08:00] [INFO] [apply.rs:1526] ["execute admin command"] [command="cmd_type: BatchSplit splits { requests { split_key: 7480000000000001FF135F698000000000FF0000040380000000FF00BC614E0419A289FF1D78000000039C3BFF327C267ACC9B0000FD new_region_id: 126725 new_peer_ids: 126726 new_peer_ids: 126727 new_peer_ids: 126728 } right_derive: true }"] [index=483855] [term=14] [peer_id=4510] [region_id=4508]
[2022/11/08 21:02:49.123 +08:00] [INFO] [split_check.rs:590] ["update approximate size and keys with accurate value"] [bucket_size=0] [bucket_count=0] [keys=155777] [size=154838518] [region_id=67989]
[2022/11/08 23:55:09.852 +08:00] [INFO] [tracker.rs:254] [slow-query] [perf_stats.internal_delete_skipped_count=0] [perf_stats.internal_key_skipped_count=82381] [perf_stats.block_read_byte=4030877] [perf_stats.block_read_count=1284] [perf_stats.block_cache_hit_count=18] [scan.range.first="Some(start: 7480000000000001135F72802F775085FE63FA end: 7480000000000001135F72803105694453C7FE)"] [scan.ranges=1] [scan.total=41191] [scan.processed_size=79535959] [scan.processed=41189] [scan.is_desc=None] [tag=analyze_full_sampling] [table_id=275] [txn_start_ts=18446744073709551615] [total_suspend_time=1.180368ms] [total_process_time=3.120613393s] [handler_build_time=2.137µs] [wait_time.snapshot=11.59µs] [wait_time.schedule=19.559µs] [wait_time=31.149µs] [total_lifetime=3.121837365s] [remote_host=ipv4:10.2.6.69:45990] [region_id=48385]
```

**Comment by overvenus** [comment]
See https://github.com/pingcap/tiflow/issues/7672#issuecomment-1340313586

**Comment by asddongmen** [comment]
duplicated with https://github.com/pingcap/tiflow/issues/10281
