### ISSUE TITLE
resource manager accesses an invalid memory address

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#7556]
### What did you do?

1. submit a dm job to engine
2. kill executor
3. Wait for a period of time, and then restart the executor

### What did you expect to see?

dm job resume normally

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x298cf12]

goroutine 49698 [running]:
[github.com/pingcap/tiflow/engine/pkg/externalresource/manager.(*Service).RemoveResource](http://github.com/pingcap/tiflow/engine/pkg/externalresource/manager.(*Service).RemoveResource)(0xc000c1c880, {0x4265e90, 0xc0016189c0}, 0xc0016189f0)
        [github.com/pingcap/tiflow/engine/pkg/externalresource/manager/service.go:161](http://github.com/pingcap/tiflow/engine/pkg/externalresource/manager/service.go:161) +0x372
[github.com/pingcap/tiflow/engine/enginepb._ResourceManager_RemoveResource_Handler.func1](http://github.com/pingcap/tiflow/engine/enginepb._ResourceManager_RemoveResource_Handler.func1)({0x4265e90, 0xc0016189c0}, {0x355d9c0?, 0xc0016189f0})
        [github.com/pingcap/tiflow/engine/enginepb/resources_grpc.pb.go:148](http://github.com/pingcap/tiflow/engine/enginepb/resources_grpc.pb.go:148) +0x78
[github.com/pingcap/tiflow/engine/pkg/rpcerror.UnaryServerInterceptor](http://github.com/pingcap/tiflow/engine/pkg/rpcerror.UnaryServerInterceptor)({0x4265e90?, 0xc0016189c0?}, {0x355d9c0, 0xc0016189f0}, 0xc0030fe760, 0xc001606a00?)
        [github.com/pingcap/tiflow/engine/pkg/rpcerror/grpc.go:140](http://github.com/pingcap/tiflow/engine/pkg/rpcerror/grpc.go:140) +0x5a
[google.golang.org/grpc.chainUnaryInterceptors.func1.1](http://google.golang.org/grpc.chainUnaryInterceptors.func1.1)({0x4265e90?, 0xc0016189c0?}, {0x355d9c0?, 0xc0016189f0?})
        [google.golang.org/grpc@v1.48.0/server.go:1129](http://google.golang.org/grpc@v1.48.0/server.go:1129) +0x5b
[github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1](http://github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1)({0x4265e90, 0xc0016189c0}, {0x355d9c0, 0xc0016189f0}, 0x36549c0?, 0xc03bccc580)
        [github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107](http://github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107) +0x87
[google.golang.org/grpc.chainUnaryInterceptors.func1.1](http://google.golang.org/grpc.chainUnaryInterceptors.func1.1)({0x4265e90?, 0xc0016189c0?}, {0x355d9c0?, 0xc0016189f0?})
        [google.golang.org/grpc@v1.48.0/server.go:1132](http://google.golang.org/grpc@v1.48.0/server.go:1132) +0x83
[google.golang.org/grpc.chainUnaryInterceptors.func1](http://google.golang.org/grpc.chainUnaryInterceptors.func1)({0x4265e90, 0xc0016189c0}, {0x355d9c0, 0xc0016189f0}, 0xc0030fe760, 0xc03a76e930)
        [google.golang.org/grpc@v1.48.0/server.go:1134](http://google.golang.org/grpc@v1.48.0/server.go:1134) +0x12b
[github.com/pingcap/tiflow/engine/enginepb._ResourceManager_RemoveResource_Handler](http://github.com/pingcap/tiflow/engine/enginepb._ResourceManager_RemoveResource_Handler)({0x34bd180?, 0xc000c1c880}, {0x4265e90, 0xc0016189c0}, 0xc001038310, 0xc000bfe220)
        [github.com/pingcap/tiflow/engine/enginepb/resources_grpc.pb.go:150](http://github.com/pingcap/tiflow/engine/enginepb/resources_grpc.pb.go:150) +0x138
[google.golang.org/grpc.(*Server).processUnaryRPC](http://google.golang.org/grpc.(*Server).processUnaryRPC)(0xc001138d20, {0x428a8e0, 0xc039785040}, 0xc001c4cea0, 0xc000bee810, 0x682ac30, 0x0)
        [google.golang.org/grpc@v1.48.0/server.go:1295](http://google.golang.org/grpc@v1.48.0/server.go:1295) +0xb2b
[google.golang.org/grpc.(*Server).handleStream](http://google.golang.org/grpc.(*Server).handleStream)(0xc001138d20, {0x428a8e0, 0xc039785040}, 0xc001c4cea0, 0x0)
        [google.golang.org/grpc@v1.48.0/server.go:1636](http://google.golang.org/grpc@v1.48.0/server.go:1636) +0xa2f
[google.golang.org/grpc.(*Server).serveStreams.func1.2()](http://google.golang.org/grpc.(*Server).serveStreams.func1.2())
        [google.golang.org/grpc@v1.48.0/server.go:932](http://google.golang.org/grpc@v1.48.0/server.go:932) +0x98
created by [google.golang.org/grpc.(*Server).serveStreams.func1](http://google.golang.org/grpc.(*Server).serveStreams.func1)
        [google.golang.org/grpc@v1.48.0/server.go:930](http://google.golang.org/grpc@v1.48.0/server.go:930) +0x28a
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
(paste Dataflow Engine version here)
```

**Comment by CharlesCheung96** [comment]
fixed by [#7516](https://github.com/pingcap/tiflow/pull/7516/files#diff-9541143a763e486d4960124f4b4284619f768ee6443367faa0e1a748f8c30b60L161)
