### ISSUE TITLE
panic: resolved ts regression

### ISSUE THREAD

**Issue by dbsid** [pingcap/tiflow#7672]
### What did you do?

create changefeed for a 100k tables dataset

```
tiup br:v6.1.2 restore db --db=bank100k --pd "pd-peer.benchbot-cdc-amd64-2xl-cdc-workload-tps-1307291-1-287:2379" --storage "s3://perftest/cdc_workload_bank_100k_t_20m_r" --s3.endpoint "" --send-credentials-to-tikv=true --check-requirements=false --ddl-batch-size 64"

tiup cdc cli changefeed create  --pd=http://pd-peer.benchbot-cdc-amd64-2xl-cdc-workload-tps-1307291-1-287:2379 --sink-uri="kafka://ds-kafka-kafka-peer:9092/cdc-topic-1669034853?protocol=canal-json&kafka-version=3.1.0&partition-num=6&max-message-bytes=67108864&replication-factor=1" --changefeed-id="simple-replication-task" --no-confirm"
```

### What did you expect to see?

no panic

### What did you see instead?

panic

```
desc = context deadline exceeded"}
{"level":"warn","ts":"2022-11-22T06:24:17.776+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00064fdc0/pd-peer:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
panic: resolved ts regression

goroutine 432261 [running]:
[go.uber.org/zap/zapcore.(*CheckedEntry).Write](http://go.uber.org/zap/zapcore.(*CheckedEntry).Write)(0xc0b7021140, {0xc2c67b18c0, 0x3, 0x3})
        [go.uber.org/zap@v1.21.0/zapcore/entry.go:232](http://go.uber.org/zap@v1.21.0/zapcore/entry.go:232) +0x44c
[go.uber.org/zap.(*Logger).Panic](http://go.uber.org/zap.(*Logger).Panic)(0xc0011a0420?, {0x332b915?, 0x1?}, {0xc2c67b18c0, 0x3, 0x3})
        [go.uber.org/zap@v1.21.0/logger.go:230](http://go.uber.org/zap@v1.21.0/logger.go:230) +0x59
[github.com/pingcap/log.Panic](http://github.com/pingcap/log.Panic)({0x332b915, 0x16}, {0xc2c67b18c0, 0x3, 0x3})
        [github.com/pingcap/log@v1.1.0/global.go:54](http://github.com/pingcap/log@v1.1.0/global.go:54) +0x10c
[github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).handleRawEvent](http://github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).handleRawEvent)(0xc09baa6e70, {0x7eff4d961508, 0xc09cf93f00}, 0xc29ceada40)
        [github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:317](http://github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:317) +0x2b0
[github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).TryHandleDataMessage](http://github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).TryHandleDataMessage)(0xc09d21dbb8?, {0x7eff4d961508?, 0xc09cf93f00?}, {0xc63beb1e50?, 0x0?, 0xc29ceada40?, 0x80?})
        [github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:346](http://github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:346) +0xc5
[github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).Receive](http://github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).Receive)(0xc09baa6e70?, {0x3a534f0, 0xc09cf93f00})
        [github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:305](http://github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:305) +0x85
[github.com/pingcap/tiflow/pkg/pipeline.(*nodeRunner).run](http://github.com/pingcap/tiflow/pkg/pipeline.(*nodeRunner).run)(0xc09d2499c0, {0x3a4acb0?, 0xc09d2187e0})
        [github.com/pingcap/tiflow/pkg/pipeline/runner.go:65](http://github.com/pingcap/tiflow/pkg/pipeline/runner.go:65) +0x277
[github.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).driveRunner](http://github.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).driveRunner)(0x125ce80?, {0x3a4acb0, 0xc09d2187e0}, {0x3a376d8?, 0xc09d249940?}, {0x3a376d8, 0xc09d2499c0})
        [github.com/pingcap/tiflow/pkg/pipeline/pipeline.go:97](http://github.com/pingcap/tiflow/pkg/pipeline/pipeline.go:97) +0xbf
created by [github.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).AppendNode](http://github.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).AppendNode)
        [github.com/pingcap/tiflow/pkg/pipeline/pipeline.go:87](http://github.com/pingcap/tiflow/pkg/pipeline/pipeline.go:87) +0x385
{"level":"warn","ts":"2022-11-22T07:22:28.124+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000e85880/pd-peer:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2022-11-22T07:26:15.855+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000e85880/pd-peer:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
```

![image](https://user-images.githubusercontent.com/2316425/203218167-166bf63e-288c-43f2-b125-3e0ee9e3b796.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```
[root@cdc-1-0 bin]# ./cdc version
Release Version: v6.1.2-3-gbc4a3dec1
Git Commit Hash: bc4a3dec15340c44c1517ab9a7fd59741352feaa
Git Branch: HEAD
UTC Build Time: 2022-11-22 00:58:51
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false
```

**Comment by dbsid** [comment]
the scripts to start cdc with GOMEMLIMIT env

```
[root@cdc-3-0 scripts]# cat run_cdc.sh
#!/bin/bash
set -e

# WARNING: This file was auto-generated. Do not edit!
#          All your edit might be overwritten!
DEPLOY_DIR=/tiup/deploy/cdc-8300
cd "${DEPLOY_DIR}" || exit 1
exec env GOMEMLIMIT=50000MiB bin/cdc server \
    --addr "0.0.0.0:8300" \
    --advertise-addr "cdc-3-peer:8300" \
    --pd "http://pd-peer:2379" \
    --data-dir="/tiup/data/cdc-8300" \
    --config conf/cdc.toml \
    --log-file "/tiup/deploy/cdc-8300/log/cdc.log" 2>> "/tiup/deploy/cdc-8300/log/cdc_stderr.log"
```

**Comment by fubinzh** [comment]
/remove-may-affects-4.0

**Comment by dbsid** [comment]
reproduce with v6.1.3 build

```
[root@cdc-3-0 bin]# ./cdc version
Release Version: v6.1.3
Git Commit Hash: 784dd7af83e06839b7eadcb2cf41cec2509bf018
Git Branch: heads/refs/tags/v6.1.3
UTC Build Time: 2022-11-25 14:51:43
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false

[root@cdc-3-0 log]# cat cdc_stderr.log
{"level":"warn","ts":"2022-11-27T12:04:19.971+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000547500/pd-peer:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"info","ts":"2022-11-27T12:04:20.435+0800","logger":"etcd-client","caller":"v3@v3.5.2/client.go:207","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
{"level":"warn","ts":"2022-11-27T12:04:20.230+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000547500/pd-peer:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
panic: resolved ts regression

goroutine 3723578 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc33ce129c0, {0xc27fb62840, 0x3, 0x3})
	go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*Logger).Panic(0xc0006f1860?, {0x338dcc6?, 0x1?}, {0xc27fb62840, 0x3, 0x3})
	go.uber.org/zap@v1.21.0/logger.go:230 +0x59
github.com/pingcap/log.Panic({0x338dcc6, 0x16}, {0xc27fb62840, 0x3, 0x3})
	github.com/pingcap/log@v1.1.0/global.go:54 +0x10c
github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).handleRawEvent(0xc1115cb760, {0x7fe88886c3c8, 0xc11e5cec80}, 0xc4ae9b9bf0)
	github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:398 +0x2b0
github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).TryHandleDataMessage(0xc11df41c18?, {0x7fe88886c3c8?, 0xc11e5cec80?}, {0xc27b8533d0?, 0x0?, 0xc4ae9b9bf0?, 0xc11df41bc0?})
	github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:427 +0xc5
github.com/pingcap/tiflow/cdc/processor/pipeline.(*sorterNode).Receive(0xc1115cb760?, {0x3ac9080, 0xc11e5cec80})
	github.com/pingcap/tiflow/cdc/processor/pipeline/sorter.go:386 +0x85
github.com/pingcap/tiflow/pkg/pipeline.(*nodeRunner).run(0xc11e9bc100, {0x3abf200?, 0xc1181c8f90})
	github.com/pingcap/tiflow/pkg/pipeline/runner.go:65 +0x277
github.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).driveRunner(0x6a80?, {0x3abf200, 0xc1181c8f90}, {0x3aa9870?, 0xc11e9bc080?}, {0x3aa9870, 0xc11e9bc100})
	github.com/pingcap/tiflow/pkg/pipeline/pipeline.go:97 +0xbf
created by github.com/pingcap/tiflow/pkg/pipeline.(*Pipeline).AppendNode
	github.com/pingcap/tiflow/pkg/pipeline/pipeline.go:87 +0x38f
```

**Comment by overvenus** [comment]
There is race condition during region merge. Assume:

1. There are two resolved ts (3 and 4) become from region A and B respectively, and A's range intersects with B's range (due to region merge).
2. region workers handle these two resolved ts concurrently.
3. 4 is forwarded to frontier before 3, and it becomes puller's resolved ts.

In this case, resolved ts regresses.

Also it may loss data if there is an event with commit ts 2 that is handled after resolved ts 4.

**Comment by charleszheng44** [comment]
> There is race condition during region merge. Assume:
> 
> 1. There are two resolved ts (3 and 4) become from region A and B respectively, and A's range intersects with B's range (due to region merge).
> 2. region workers handle these two resolved ts concurrently.
> 3. 4 is forwarded to frontier before 3, and it becomes puller's resolved ts.
> 
> In this case, resolved ts regresses.
> 
> Also it may loss data if there is an event with commit ts 2 that is handled after resolved ts 4.
> 
> <img alt="image" width="480" src="https://user-images.githubusercontent.com/2150711/206078481-bc5b7bb4-876c-4e85-b956-d84c90518849.png">

How to mitigate this issue?

**Comment by charleszheng44** [comment]
@overvenus do you know how to mitigate this issue?

**Comment by asddongmen** [comment]
never happen again
