### ISSUE TITLE
CDC panic after rolling restart cdc

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#7734]
### What did you do?

1. Start changefeed with storage sink
2. Run workload
3. Rolling restart TiCDC

### What did you expect to see?

should not panic

### What did you see instead?

CDC panic

```
[root@centos76_vm ticdc]# cat test.log
[WARN] TiCDC server data-dir is not set. Please use `cdc server --data-dir` to start the cdc server if possible.
panic: runtime error: index out of range [3] with length 3

goroutine 1078 [running]:
github.com/google/btree.(*items[...]).insertAt(...)
        github.com/google/btree@v1.1.2/btree_generic.go:176
github.com/google/btree.(*node[...]).maybeSplitChild(0xc00c003a00, 0x3, 0x1f)
        github.com/google/btree@v1.1.2/btree_generic.go:285 +0x507
github.com/google/btree.(*node[...]).insert(0xc00c003a00, {0x2307e, {{{0xc00241ab00, 0x8}, {0xc0025c0398, 0x7}, 0x57, 0x0}, 0x612f969086c00a4}, 0xc00240bfc8, ...}, ...)
        github.com/google/btree@v1.1.2/btree_generic.go:304 +0x405
github.com/google/btree.(*BTreeG[...]).ReplaceOrInsert(0xc006fa63e0, {0x2307e, {{{0xc00241ab00, 0x8}, {0xc0025c0398, 0x7}, 0x57, 0x0}, 0x612f969086c00a4}, 0xc00240bfc8, ...})
        github.com/google/btree@v1.1.2/btree_generic.go:702 +0x445
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*defragmenter).registerFrag(...)
        github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/defragmenter.go:38
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*dmlWorker).backgroundDispatchMsgs.func1()
        github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/dml_worker.go:206 +0x7e9
created by github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*dmlWorker).backgroundDispatchMsgs
        github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/dml_worker.go:160 +0x14a
panic: runtime error: index out of range [1] with length 1

goroutine 1077 [running]:
github.com/google/btree.(*node[...]).growChildAndRemove(0xc00c003a00, 0x0, {0x0, {{{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0x0}, ...}, ...)
        github.com/google/btree@v1.1.2/btree_generic.go:448 +0x13e6
github.com/google/btree.(*node[...]).remove(0xc00c003a00, {0x0, {{{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0x0}, 0x0, ...}, ...)
        github.com/google/btree@v1.1.2/btree_generic.go:396 +0x925
github.com/google/btree.(*BTreeG[...]).deleteItem(0xc006fa63e0, {0x0, {{{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0x0}, 0x0, ...}, ...)
        github.com/google/btree@v1.1.2/btree_generic.go:734 +0x16c
gitub.com/google/btree.(*BTreeG[...]).DeleteMin(0x404217?)
        github.com/google/btree@v1.1.2/btree_generic.go:719 +0xbf
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*defragmenter).reassmebleFrag(0xc008f45260)
        github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/defragmenter.go:44 +0x68
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*dmlWorker).backgroundFlushMsgs.func1()
        github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/dml_worker.go:118 +0x6f3
created by github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*dmlWorker).backgroundFlushMsgs
        github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/dml_worker.go:92 +0xad
```
![image](https://user-images.githubusercontent.com/7403864/204289361-cedd6f2b-ee03-4694-9123-e4192b35977a.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
/ # /tidb-server -V
Release Version: v6.5.0-alpha
Edition: Community
Git Commit Hash: 5b9d96b9486a070a79279252d94ce0bc45f2e0bc
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-28 11:15:07
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

```

Upstream TiKV version (execute `tikv-server --version`):

```console
/ # /tikv-server -V
TiKV 
Release Version:   6.5.0-alpha
Edition:           Community
Git Commit Hash:   bfe29655a2a1634c268a7fb3986892be7dc1f305
Git Commit Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time:    2022-11-28 11:07:57
Rust Version:      rustc 1.67.0-nightly (96ddd32c4 2022-11-14)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
/ # 

```

TiCDC version (execute `cdc version`):

```console
bash-5.1# /cdc version
Release Version: v6.5.0-alpha
Git Commit Hash: 07657c5fa7035f4dc02f82473c50d516ff7b58ff
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-28 11:06:34
Go Version: go version go1.19.3 linux/amd64
Failpoint Build: false

```

**Comment by zhaoxinyu** [comment]
fixed by #7547
