### ISSUE TITLE
[PANIC] factory.(*SortEngineFactory).Create() reports MANIFEST set current failed ... no such file or directory

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#7805]
### What did you do?

Run integration tests

### What did you expect to see?

No error

### What did you see instead?

```console
2022/12/05 14:50:52 MANIFEST set current failed: open /tmp/tidb_cdc_test/http_api/cdc_data/tmp/sorter/0000/temporary.000001.dbtmp: no such file or directory
```

In TiCDC stderr.log

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/17195/pipeline

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
release-6.5
```

Upstream TiKV version (execute `tikv-server --version`):

```console
release-6.5
```

TiCDC version (execute `cdc version`):

```console
release-6.5
```

**Comment by overvenus** [comment]
Maybe relates to #7804

**Comment by asddongmen** [comment]
After this error, there is a panic:
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6805248]

goroutine 818 [running]:
[github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).GetAllCurrentTableIDs(0x0)](http://github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).GetAllCurrentTableIDs(0x0))
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:731](http://github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:731) +0x68
[github.com/pingcap/tiflow/cdc/processor.(*processor).refreshMetrics(0xc001510000)](http://github.com/pingcap/tiflow/cdc/processor.(*processor).refreshMetrics(0xc001510000))
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/cdc/processor/processor.go:1255](http://github.com/pingcap/tiflow/cdc/processor/processor.go:1255) +0x139
[github.com/pingcap/tiflow/cdc/processor.(*processor).Tick](http://github.com/pingcap/tiflow/cdc/processor.(*processor).Tick)(0xc001510000, {0x913d7c0, 0xc003156510})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/cdc/processor/processor.go:653](http://github.com/pingcap/tiflow/cdc/processor/processor.go:653) +0x9e7
[github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick](http://github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick)(0xc000cc0740, {0x7f991041d388?, 0xc00170cb60}, {0x9103800?, 0xc0006bbce0})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/cdc/processor/manager.go:128](http://github.com/pingcap/tiflow/cdc/processor/manager.go:128) +0x865
[github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run](http://github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run)(0xc002926790, {0x7f991041d388, 0xc00170cb60}, 0xc000a0fad0, 0x2faf080, {0x74b7118, 0x9})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290](http://github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290) +0x1627
[github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker](http://github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker)(0xc0014a6000, {0x913d860?, 0xc00170cb60}, {0x7f9973424028, 0xc000cc0740}, {0x9103800, 0xc0006bbce0}, 0xc00170c020?, {0x74b7118, 0x9})
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/cdc/capture/capture.go:515](http://github.com/pingcap/tiflow/cdc/capture/capture.go:515) +0x226
[github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()](http://github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3())
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/[github.com/pingcap/tiflow/cdc/capture/capture.go:369](http://github.com/pingcap/tiflow/cdc/capture/capture.go:369) +0x356
[golang.org/x/sync/errgroup.(*Group).Go.func1()](http://golang.org/x/sync/errgroup.(*Group).Go.func1())
	/go/pkg/mod/[golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75](http://golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75) +0x87
created by [golang.org/x/sync/errgroup.(*Group).Go](http://golang.org/x/sync/errgroup.(*Group).Go)
	/go/pkg/mod/[golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72](http://golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72) +0x12f
```

ref:https://ci.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/6070/pipeline/148

**Comment by asddongmen** [comment]
fix by https://github.com/pingcap/tiflow/pull/7808
