### ISSUE TITLE
Panic when using pull-based sink

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tiflow#7865]
### What did you do?

Run the integration tests. 

### What did you expect to see?

panic: interface conversion: interface {} is nil, not *sinkmanager.tableSinkWrapper

goroutine 1558 [running]:
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).UpdateReceivedSorterResolvedTs(0xc000cb8280, 0x94, 0x1a7cc5b?)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:608 +0x3b7
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).handleEvents(0xc001285d90, 0x1, 0xc002d78480, 0xc000124780)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:449 +0x11fc
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.New.func1(0x1)
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:89 +0x174
created by github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.New
	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:87 +0x56b

### What did you see instead?

It works normally.

### Versions of the cluster

master

**Comment by hi-rustin** [comment]
See: https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/17373/pipeline
