### ISSUE TITLE
cdc continues panic with `schedulerv3: impossible spans`

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tiflow#7931]
### What did you do?

- start three cdc nodes.
- create a changefeed with 3000 sysbench tables.

### What did you see instead?

ticdc continues panic

```go
[2022/12/19 10:28:10.796 +08:00] [PANIC] [reconciler.go:85] ["schedulerv3: impossible spans"] [changefeed=cdc-cf-3] [namespace=default] [tableID=90] [spanStart={table_id:90,start_key:7480000000000000ff5a5f720000000000fa}] [spanEnd={table_id:90,start_key:7480000000000000ff5a5f730000000000fa}] [stack="github.com/pingcap/tiflow/cdc/scheduler/internal/v3/keyspan.(*Reconciler).Reconcile
        github.com/pingcap/tiflow/cdc/scheduler/internal/v3/keyspan/reconciler.go:85
github.com/pingcap/tiflow/cdc/scheduler/internal/v3.(*coordinator).poll
        github.com/pingcap/tiflow/cdc/scheduler/internal/v3/coordinator.go:313
github.com/pingcap/tiflow/cdc/scheduler/internal/v3.(*coordinator).Tick
        github.com/pingcap/tiflow/cdc/scheduler/internal/v3/coordinator.go:128
github.com/pingcap/tiflow/cdc/owner.(*changefeed).tick
        github.com/pingcap/tiflow/cdc/owner/changefeed.go:308
github.com/pingcap/tiflow/cdc/owner.(*changefeed).Tick
        github.com/pingcap/tiflow/cdc/owner/changefeed.go:191
github.com/pingcap/tiflow/cdc/owner.(*ownerImpl).Tick
        github.com/pingcap/tiflow/cdc/owner/owner.go:215
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run
        github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker
        github.com/pingcap/tiflow/cdc/capture/capture.go:514
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner
        github.com/pingcap/tiflow/cdc/capture/capture.go:477
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func2
        github.com/pingcap/tiflow/cdc/capture/capture.go:342
golang.org/x/sync/errgroup.(*Group).Go.func1
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75"]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

master@https://github.com/pingcap/tiflow/commit/31a235f84d7cfe9fa376b21e0d55ac752fb01923

**Comment by hicqu** [comment]
Same problem with 10000 tables：
```
panic: schedulerv3: impossible spans

goroutine 763 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x5?, 0x5?, {0x0?, 0x0?, 0xc0142805c0?})
        go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0144132b0, {0xc0005a0c80, 0x5, 0x5})
        go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc0005a0c80?, {0x3944930?, 0xc003fa8de0?}, {0xc0005a0c80, 0x5, 0x5})
        go.uber.org/zap@v1.23.0/logger.go:251 +0x59
github.com/pingcap/log.Panic({0x3944930?, 0xc0140b4e70?}, {0xc0005a0c80?, 0x12?, 0x0?})
        github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x8b
github.com/pingcap/tiflow/cdc/scheduler/internal/v3/keyspan.(*Reconciler).Reconcile(0xc0140a3620, {0x7f5f52663198, 0xc013e2ad68}, {0xc002bc4000, 0x2710, 0x19?}, 0x38ff319?, 0x10?)
        github.com/pingcap/tiflow/cdc/scheduler/internal/v3/keyspan/reconciler.go:85 +0xf35
github.com/pingcap/tiflow/cdc/scheduler/internal/v3.(*coordinator).poll(0xc002274bb0, {0x7f5f52663198, 0xc013e2ad68}, 0xc0153d82f8?, {0xc002bc4000, 0x2710, 0x3000}, 0xc00225b7d0)
        github.com/pingcap/tiflow/cdc/scheduler/internal/v3/coordinator.go:313 +0xaae
github.com/pingcap/tiflow/cdc/scheduler/internal/v3.(*coordinator).Tick(0x3919ce1?, {0x7f5f52663198?, 0xc013e2ad68?}, 0x3406aa0?, {0xc002bc4000?, 0x0?, 0x0?}, 0x0?)
        github.com/pingcap/tiflow/cdc/scheduler/internal/v3/coordinator.go:128 +0x139
github.com/pingcap/tiflow/cdc/owner.(*changefeed).tick(0xc002ed64e0, {0x4216dd0?, 0xc013e2ad68}, 0xffffffffffffffff?)
        github.com/pingcap/tiflow/cdc/owner/changefeed.go:308 +0x91f
github.com/pingcap/tiflow/cdc/owner.(*changefeed).Tick(0xc002ed64e0, {0x4216ce0?, 0xc013e2ad50}, 0xc00225ed20?)
        github.com/pingcap/tiflow/cdc/owner/changefeed.go:191 +0x187
github.com/pingcap/tiflow/cdc/owner.(*ownerImpl).Tick(0xc00225c500, {0x7f5f52b21958?, 0xc000447580}, {0x41db368?, 0xc00225ed20})
        github.com/pingcap/tiflow/cdc/owner/owner.go:215 +0x4b1
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc002274210, {0x7f5f52b21958, 0xc000447580}, 0xc000aa6f60, 0x2faf080, {0x38dab4d, 0x5})
        github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0xfa6
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc0022a8120, {0x4216d80?, 0xc000447580}, {0x7f5f52a1cd88, 0xc00225c500}, {0x41db368, 0xc00225ed20}, 0x3559aa0?, {0x38dab4d, 0x5})
        github.com/pingcap/tiflow/cdc/capture/capture.go:514 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner(0xc0022a8120, {0x4216d80?, 0xc0005bc200})
        github.com/pingcap/tiflow/cdc/capture/capture.go:477 +0x7bb
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func2()
        github.com/pingcap/tiflow/cdc/capture/capture.go:342 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
panic: schedulerv3: impossible spans

```
