### ISSUE TITLE
CDC panic: onResolvedTsMsg is called for an invalid table, when running redo log changefeed against GCS

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8024]
### What did you do?

- deploy tidb cluster
- create eventual consistency changefeed, and use GCS as target storage
- Run workload

### What did you expect to see?

CDC should run without panic

### What did you see instead?

CDC panic

```
kubectl logs -p upstream-ticdc-0 --kubeconfig kubeconfig.yml -n cdc-fb-x7bfs
[WARN] TiCDC server data-dir is not set. Please use `cdc server --data-dir` to start the cdc server if possible.
panic: onResolvedTsMsg is called for an invalid table

goroutine 811 [running]:
[github.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).onResolvedTsMsg](http://github.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).onResolvedTsMsg)(0xc0021dda00, {0x9c, {0xc0461f4ea0, 0x12, 0x18}, {0xc0461f4eb8, 0x12, 0x18}}, 0x616025cac98000d)
        [github.com/pingcap/tiflow/cdc/redo/manager.go:481](http://github.com/pingcap/tiflow/cdc/redo/manager.go:481) +0x1c5
[github.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).bgUpdateLog.func3()](http://github.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).bgUpdateLog.func3())
        [github.com/pingcap/tiflow/cdc/redo/manager.go:557](http://github.com/pingcap/tiflow/cdc/redo/manager.go:557) +0x9cb
[github.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).bgUpdateLog](http://github.com/pingcap/tiflow/cdc/redo.(*ManagerImpl).bgUpdateLog)(0xc0021dda00, {0x4231230, 0xc002675da0}, 0x7d0, 0xc0021c23c0)
        [github.com/pingcap/tiflow/cdc/redo/manager.go:597](http://github.com/pingcap/tiflow/cdc/redo/manager.go:597) +0x93c
created by [github.com/pingcap/tiflow/cdc/redo.NewManager](http://github.com/pingcap/tiflow/cdc/redo.NewManager)
        [github.com/pingcap/tiflow/cdc/redo/manager.go:187](http://github.com/pingcap/tiflow/cdc/redo/manager.go:187) +0x46b
```

### Versions of the cluster

bash-5.1# /cdc version
Release Version: v6.5.0-master-dirty
Git Commit Hash: 941aa3feff4290c93794e0aa44fc081389dd4488
Git Branch: master
UTC Build Time: 2023-01-05 03:34:56
Go Version: go version go1.19.1 linux/amd64
Failpoint Build: false

**Comment by CharlesCheung96** [comment]
The reason for the panic is that some table's resolved event was sent to redoManager before addTable was called. And we need to investigate problems outside the redo module.
