### ISSUE TITLE
cdc stuck when closing sinkv2

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#8285]
### What did you do?

1. run sysbench to prepare 10 million rows
2. create changefeed with redo enabled

### What did you expect to see?

replcate success

### What did you see instead?

```log
goroutine 538 [semacquire, 814 minutes]:
sync.runtime_Semacquire(0x0?)
	runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc000af5aa0?)
	sync/waitgroup.go:139 +0x52
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worker).Close(0xc000b45380)
	github.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:100 +0x1fc
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*sink).Close(0xc0024f22c0)
	github.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/txn_sink.go:124 +0x65
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/factory.(*SinkFactory).Close(0x3af42a1?)
	github.com/pingcap/tiflow/cdc/sinkv2/eventsink/factory/factory.go:146 +0x34
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).Close(0xc000717b80)
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:897 +0x51a
github.com/pingcap/tiflow/cdc/processor.(*processor).Close(0xc00277a840, {0x44336d0, 0xc07ee08120})
	github.com/pingcap/tiflow/cdc/processor/processor.go:945 +0x3c9
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).closeProcessor(0xc00215f9f0, {{0xc0020b2832?, 0xc07ee08120?}, {0xc0020b284a?, 0x74184c0?}}, {0x44336d0, 0xc07ee08120})
	github.com/pingcap/tiflow/cdc/processor/manager.go:162 +0xe5
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc00215f9f0, {0x7fe5038c3cb0?, 0xc0007fdb00}, {0x43f7598?, 0xc000825020})
	github.com/pingcap/tiflow/cdc/processor/manager.go:140 +0x4ea
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc000ed8370, {0x7fe5038c3cb0, 0xc0007fdb00}, 0xc000b8cc30, 0x2faf080, {0x3abee3c, 0x9})
	github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0xfa6
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc000a221e0, {0x4433770?, 0xc0007fdb00}, {0x7fe5038c3ce8, 0xc00215f9f0}, {0x43f7598, 0xc000825020}, 0x0?, {0x3abee3c, 0x9})
	github.com/pingcap/tiflow/cdc/capture/capture.go:500 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()
	github.com/pingcap/tiflow/cdc/capture/capture.go:354 +0x299
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```
```log
[2023/02/16 15:34:04.390 +00:00] [ERROR] [worker.go:129] ["Transaction sink worker panics"] [r="\"send on closed channel\""] [stacktrace="github.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worker).runBackgroundLoop.func1.2\n\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:129\nruntime.gopanic\n\truntime/panic.go:884\nruntime.chansend\n\truntime/chan.go:206\nruntime.chansend1\n\truntime/chan.go:145\ngithub.com/pingcap/tiflow/pkg/causality.(*ConflictDetector[...]).Add.func1.1\n\tgithub.com/pingcap/tiflow/pkg/causality/conflict_detector.go:83\ngithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worker).doFlush\n\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:222\ngithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worker).runBackgroundLoop.func1\n\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:159"]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)

Release Version: v6.5.0-master
Git Commit Hash: 4519a44a92f2402ae384dfa8361bccd2041e0289
Git Branch: master
UTC Build Time: 2023-02-16 16:39:23
Go Version: go version go1.19.2 linux/amd64
Failpoint Build: false
```

**Comment by CharlesCheung96** [comment]
somle logs:
[stuck.log](https://github.com/pingcap/tiflow/files/10763962/stuck.log)
[stuck_cdc.log.tar.gz](https://github.com/pingcap/tiflow/files/10763969/stuck_cdc.log.tar.gz)
