### ISSUE TITLE
Panic on kafka-consumer in test `changefeed_error`

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#8692]
### What did you do?

Run CI

### What did you expect to see?

No panic.

### What did you see instead?

```
[2023-03-27T11:01:01.902Z] panic: partition resolved ts fallback

[2023-03-27T11:01:01.902Z] 

[2023-03-27T11:01:01.902Z] goroutine 261 [running]:

[2023-03-27T11:01:01.902Z] go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x3?, 0x3?, {0x0?, 0x0?, 0xc001d038a0?})

[2023-03-27T11:01:01.902Z] 	go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65

[2023-03-27T11:01:01.902Z] go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00197e820, {0xc0019c8180, 0x3, 0x3})

[2023-03-27T11:01:01.902Z] 	go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec

[2023-03-27T11:01:01.902Z] go.uber.org/zap.(*Logger).Panic(0xc000100000?, {0x37af3c8?, 0x0?}, {0xc0019c8180, 0x3, 0x3})

[2023-03-27T11:01:01.902Z] 	go.uber.org/zap@v1.24.0/logger.go:258 +0x59

[2023-03-27T11:01:01.902Z] github.com/pingcap/log.Panic({0x37af3c8?, 0x30b1320?}, {0xc0019c8180?, 0xc00220c27f?, 0x8?})

[2023-03-27T11:01:01.902Z] 	github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x8b

[2023-03-27T11:01:01.903Z] main.(*Consumer).ConsumeClaim(0xc000175c20, {0x3fab7d0, 0xc00056c360}, {0x3f9a440, 0xc0008d46f0})

[2023-03-27T11:01:01.903Z] 	github.com/pingcap/tiflow/cmd/kafka-consumer/main.go:614 +0xcf3

[2023-03-27T11:01:01.903Z] github.com/Shopify/sarama.(*consumerGroupSession).consume(0xc00056c360, {0xc00053c3c0, 0x1b}, 0x3)

[2023-03-27T11:01:01.903Z] 	github.com/Shopify/sarama@v1.36.0/consumer_group.go:824 +0x262

[2023-03-27T11:01:01.903Z] github.com/Shopify/sarama.newConsumerGroupSession.func2({0xc00053c3c0?, 0x0?}, 0x0?)

[2023-03-27T11:01:01.903Z] 	github.com/Shopify/sarama@v1.36.0/consumer_group.go:749 +0x76

[2023-03-27T11:01:01.903Z] created by github.com/Shopify/sarama.newConsumerGroupSession

[2023-03-27T11:01:01.903Z] 	github.com/Shopify/sarama@v1.36.0/consumer_group.go:741 +0x4b4

[2023-03-27T11:01:01.903Z] make: *** [integration_test_kafka] Error 1

```

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/18675/pipeline/

### Versions of the cluster

TiCDC version (execute `cdc version`):

2023/03/28 master branch

**Comment by nongfushanquan** [comment]
since the consumer has been refactored, and the issue didn't reproduce for a long time ,so close it .
