### ISSUE TITLE
storage sink stuck at defragmenter.close

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#8698]
```log
goroutine 590 [semacquire, 60 minutes]:
sync.runtime_Semacquire(0x0?)
	runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc006e28688?)
	sync/waitgroup.go:139 +0x52
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*defragmenter).close(...)
	github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/defragmenter.go:101
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage.(*dmlSink).Close(0xc004d9d780)
	github.com/pingcap/tiflow/cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go:180 +0x2f
github.com/pingcap/tiflow/cdc/sinkv2/eventsink/factory.(*SinkFactory).Close(0xc004d1fc70?)
	github.com/pingcap/tiflow/cdc/sinkv2/eventsink/factory/factory.go:115 +0x34
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).Close(0xc004e138c0)
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:698 +0x79
github.com/pingcap/tiflow/cdc/processor.(*processor).Close(0xc00458c000, {0x4137680, 0xc000cdbc60})
	github.com/pingcap/tiflow/cdc/processor/processor.go:1294 +0x591
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).closeProcessor(0xc001de6bc0, {{0xc001f10c98?, 0xc004c73890?}, {0xc001f10cb0?, 0xc10119878ede5616?}}, {0x4137680, 0xc000cdbc60})
	github.com/pingcap/tiflow/cdc/processor/manager.go:159 +0x359
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc001de6bc0, {0x7f5e3fc7acd8?, 0xc000cdbc60}, {0x40fe328?, 0xc0021c8de0})
	github.com/pingcap/tiflow/cdc/processor/manager.go:138 +0x61c
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc000d5bce0, {0x7f5e3fc7acd8, 0xc000cdbc60}, 0xc001eb6840, 0x2faf080, {0x38305da, 0x9})
	github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0xfa6
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc000da2000, {0x4137680?, 0xc000cdbc60}, {0x7f5e3fc7ad10, 0xc001de6bc0}, {0x40fe328, 0xc0021c8de0}, 0x1?, {0x38305da, 0x9})
	github.com/pingcap/tiflow/cdc/capture/capture.go:515 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()
	github.com/pingcap/tiflow/cdc/capture/capture.go:369 +0x299
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by CharlesCheung96** [comment]
Only affect release6.5.0, fixed in [pr8585](https://github.com/pingcap/tiflow/pull/8585/files#diff-bf74ae2e12e417442cfc6761be711916b374a93d7882ad2aeee58c776ee3882cR92)
