### ISSUE TITLE
A Panic occurs in ddl_manager.go when replicating drop table DDL.

### ISSUE THREAD

**Issue by asddongmen** [pingcap/tiflow#8714]
### What did you do?

run syncpoint test.

### What did you expect to see?

no panic

### What did you see instead?

```log
panic: checkpointTs is greater than next ddl commitTs

goroutine 740 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc0055e1ad0, {0xa71d9c6?, 0x36?, 0xc004f36000?})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0xa8
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0055e1ad0, {0xc002ed4f80, 0x2, 0x2})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x586
go.uber.org/zap.(*Logger).Panic(0xd4c6f90?, {0x7fd5b37, 0x2e}, {0xc002ed4f80, 0x2, 0x2})
	/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x6e
github.com/pingcap/log.Panic({0x7fd5b37, 0x2e}, {0xc002ed4f80, 0x2, 0x2})
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x74
github.com/pingcap/tiflow/cdc/owner.(*ddlManager).tick(0xc002e248c0, {0x7fef2c4af368, 0xc005f13050}, 0x61cdaf3d1c80000, 0x0?)
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/owner/ddl_manager.go:270 +0x1159
github.com/pingcap/tiflow/cdc/owner.(*changefeed).tick(0xc000e34b60, {0x9ba2800?, 0xc005f13050}, 0xc000000001?)
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/owner/changefeed.go:298 +0x4c7
github.com/pingcap/tiflow/cdc/owner.(*changefeed).Tick(0xc000e34b60, {0x9ba2710?, 0xc005f13038}, 0xc0015f0f60?)
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/owner/changefeed.go:209 +0x396
github.com/pingcap/tiflow/cdc/owner.(*ownerImpl).Tick(0xc00051e850, {0x7fef90622ef0?, 0xc001654640}, {0x9b6fad0?, 0xc0015f0f60})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/owner/owner.go:201 +0xc67
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc000270210, {0x7fef90622ef0, 0xc001654640}, 0xc001848b70, 0x2faf080, {0x7efdf4a, 0x5})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/pkg/orchestrator/etcd_worker.go:290 +0x1b47
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc0018262a0, {0x9ba27b0?, 0xc001654640}, {0x7fef6602c5d8, 0xc00051e850}, {0x9b6fad0, 0xc0015f0f60}, 0x0?, {0x7efdf4a, 0x5})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/capture/capture.go:510 +0x30a
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner(0xc0018262a0, {0x9ba27b0?, 0xc000aa2060})
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/capture/capture.go:461 +0x146b
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()
	/home/jenkins/agent/workspace/pingcap/tiflow/pull_cdc_integration_test/tiflow/cdc/capture/capture.go:327 +0x79
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x83
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x12f

```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by asddongmen** [comment]
This panic does not cause data inconsistent.

**Comment by asddongmen** [comment]
This Panic only occurs when executing the drop table ddl, and the longer the execution time of this ddl, the higher the probability of the Panic occurring.

Assuming there is a ddl: drop table t1, with a commitTs of `10`, referred to as d1 below, let's study in detail how d1 will be processed.

Owner Tick round 1:

1. Assume the current `checkpointTs` is `7`.
2. `ddlManager` receives d1.
3. `ddlManager` executes `m.allPhysicalTables(ctx)` to obtain the cached table information, `tables = [t1]`
4. ddlManager executes [m.cleanCache()](https://github.com/pingcap/tiflow/pull/8716/files#diff-22d25e82af60f580f09cf3ace50f4c276f10b5e0d29beb6f4999598605bb39f4L215)  to clear the table information in cache.
5. It will set the `tableBarrier` of t1 to `10`, and then return `tables = [t1]` together to the caller.
6. `scheduler` will broadcast `tableBarrier` to the `processor` to stop the progress of t1 at `10`.
7. `scheduler.tick()` calculates that `newCheckpointTs` is `8` and is updated to Etcd by the `owner`.

Owner Tick round 2:

1. The current `checkpointTs` is `8`.
2. `ddlManager` executes `m.allPhysicalTables(ctx)` to obtain the table information at `ts = 8`, `tables = [t1]`.
3. Since `checkpointTs` has not advanced to `10`, d1 will not be executed.
4. `scheduler.tick()` calculates that `newCheckpointTs` is `10` and is updated to Etcd by the `owner`.

Owner tick round 3:

1. The current `checkpointTs` is `10`.
2. `ddlManager` executes `m.allPhysicalTables(ctx)` to obtain the cached table information, `tables = [t1]`.
3. Since `checkpointTs` has advanced to `10`, which is the same as d1's `commitTs`, it will enter the logic of executing d1.
4. `ddlManager` executes [m.cleanCache()](https://github.com/pingcap/tiflow/pull/8716/files#diff-22d25e82af60f580f09cf3ace50f4c276f10b5e0d29beb6f4999598605bb39f4L289)to clear the table information cache, and then calls `m.executeDDL()` to execute d1.
5. `scheduler.tick()` will continue to broadcast t1 `tableBarrier = 10` to the `processor`.

Owner tick round 4:

1. The current `checkpointTs` is `10`.
2. ddlManager executes `m.allPhysicalTables(ctx)` to obtain the table information at `ts = 10`, `tables = []`.
3. `ddlManager` calls `m.executeDDL()` to check whether d1 has been executed, and finds that the ddl has not been completed.
4. `scheduler.tick()` will continue to broadcast t1’s `tableBarrier = 10` to the `processor` , and since `tables =[]` returned by ddlManager, `scheduler` will send a scheduling task to the `processor` to **remove table t1.**
5. `processor` removes table t1.

Owner tick round 5:

1. The current `checkpointTs` is `10`.
2. `ddlManager` executes `m.allPhysicalTables(ctx)` to obtain the cached table information, `tables = []`.
3. `ddlManager` calls `m.executeDDL()` to check whether d1 has been executed, and finds that d1 has not been completed.
4. Since t1 **has been deleted** by the `processor`, the `checkpointTs` calculated by `scheduler.tick()` is no longer affected by t1's `tableBarrier = 10`; `newCheckpointTs` = 11 is calculated, and is updated to Etcd by the owner.

Owner tick round 6:

1. The current `checkpointTs` is `11`.
2. Enter the [panic logic.](https://github.com/pingcap/tiflow/pull/8716/files#diff-22d25e82af60f580f09cf3ace50f4c276f10b5e0d29beb6f4999598605bb39f4R272)
