### ISSUE TITLE
changefeed stucks peer message client detected error

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#8802]
### What did you do?

1. Start kafka changefeed
2. Inject kafka broker failure sometime
3. Check changefeed status when kafka failure restored

### What did you expect to see?

1. CDC changefeed should be normal

### What did you see instead?

1. CDC changefeed stucks
![image](https://user-images.githubusercontent.com/7403864/232666817-92e2da23-b49f-477e-87ef-2787d002cd18.png)

![img_v2_a432e63d-fb45-486a-8f33-fbb379e1e41g](https://user-images.githubusercontent.com/7403864/232667054-74264665-0559-4178-a887-795607eec3f4.jpg)

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
[root@upstream-ticdc-0 /]# /cdc version
Release Version: v7.1.0-alpha
Git Commit Hash: d35ab225966b88cd6415b90a3d69b64dbcb65f54
Git Branch: heads/refs/tags/v7.1.0-alpha
UTC Build Time: 2023-04-14 11:34:16
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false

```

**Comment by fubinzh** [comment]
related logs:
[ticdc-1.log](https://github.com/pingcap/tiflow/files/11257723/ticdc-1.log)
[ticdc.log](https://github.com/pingcap/tiflow/files/11257724/ticdc.log)
[case.log](https://github.com/pingcap/tiflow/files/11257725/case.log)

**Comment by asddongmen** [comment]
It's stuck in processor initializing:
```log
goroutine 882 [select, 534 minutes]:
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).WaitForReady(0xc10ba33cc0, {0x47e5490?, 0xc6e94c0720?})
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:893 +0x6c
github.com/pingcap/tiflow/cdc/processor.(*component[...]).spawn(0x47c52c0, {0x47e5490, 0xc6e94c0720})
	github.com/pingcap/tiflow/cdc/processor/processor.go:995 +0x223
github.com/pingcap/tiflow/cdc/processor.(*processor).lazyInitImpl(0xc10835f680, {0x47fd510, 0xc016909ad0})
	github.com/pingcap/tiflow/cdc/processor/processor.go:671 +0xf65
github.com/pingcap/tiflow/cdc/processor.(*processor).tick(0xc10835f680, {0x47fd510?, 0xc016909ad0})
	github.com/pingcap/tiflow/cdc/processor/processor.go:554 +0x84
github.com/pingcap/tiflow/cdc/processor.(*processor).Tick(0xc10835f680, {0x47fd510, 0xc016909ad0})
	github.com/pingcap/tiflow/cdc/processor/processor.go:482 +0x3a5
github.com/pingcap/tiflow/cdc/processor.(*managerImpl).Tick(0xc000730870, {0x7feccf2d46a8?, 0xc000644960}, {0x47cbbc0?, 0xc001924f60?})
	github.com/pingcap/tiflow/cdc/processor/manager.go:141 +0x477
github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run(0xc002e82370, {0x7feccf2d46a8, 0xc000644960}, 0xc0010ec480, 0x2faf080, {0x3ead0a9, 0x9})
	github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0xfa6
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker(0xc00040a620, {0x47fd5b0?, 0xc000644960}, {0x7feccf4a0418, 0xc000730870}, {0x47cbbc0, 0xc001924f60}, 0x0?, {0x3ead0a9, 0x9})
	github.com/pingcap/tiflow/cdc/capture/capture.go:510 +0x185
github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func4()
	github.com/pingcap/tiflow/cdc/capture/capture.go:352 +0x299
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by asddongmen** [comment]
This issue also occurs in 7.1 performance testing enviromment.
