### ISSUE TITLE
avro panic on incorrect type conversion of type.Time

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#8950]
### What did you do?

run some workload, execute some ddl

### What did you expect to see?

nothing

### What did you see instead?

```
panic: interface conversion: interface {} is types.Time, not int64

goroutine 1249 [running]:
github.com/pingcap/tiflow/pkg/sink/codec/avro.columnToAvroData(0xc021579380, 0xc024023a70?, {0xc003017cce?, 0xb?}, {0xc003017cf8?, 0xc022517870?})
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:833 +0x1119
github.com/pingcap/tiflow/pkg/sink/codec/avro.rowToAvroData(0xc024023a40, 0x62029364a400006, {0x4812d00, 0x1}, 0x1, {0xc003017cce, 0x6}, {0xc003017cf8, 0x6})
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:630 +0x111
github.com/pingcap/tiflow/pkg/sink/codec/avro.(*BatchEncoder).avroEncode(0xc003e4e280, {0x4859e68, 0xc003039a40}, 0xc018cdbe40, {0xc003017c7c, 0xd}, 0xff?)
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:279 +0x390
github.com/pingcap/tiflow/pkg/sink/codec/avro.(*BatchEncoder).AppendRowChangedEvent(0xc003e4e280, {0x4859e68, 0xc003039a40}, {0xc003017c7c, 0xd}, 0xc018cdbe40, 0xc022672480)
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:113 +0x1d8
github.com/pingcap/tiflow/pkg/sink/codec.(*encoderGroup).runEncoder(0xc003564d80, {0x4859e68, 0xc003039a40}, 0x7)
        github.com/pingcap/tiflow/pkg/sink/codec/encoder_group.go:116 +0x385
github.com/pingcap/tiflow/pkg/sink/codec.(*encoderGroup).Run.func2()
        github.com/pingcap/tiflow/pkg/sink/codec/encoder_group.go:95 +0x2c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
panic: interface conversion: interface {} is types.Time, not int64

goroutine 912 [running]:
github.com/pingcap/tiflow/pkg/sink/codec/avro.columnToAvroData(0xc0168beae0, 0xc02328bd10?, {0xc0005495ce?, 0xc?}, {0xc0005495f8?, 0xc01b6ff870?})
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:818 +0xd39
github.com/pingcap/tiflow/pkg/sink/codec/avro.rowToAvroData(0xc02328bce0, 0x62029364a400006, {0x4812d00, 0x1}, 0x1, {0xc0005495ce, 0x6}, {0xc0005495f8, 0x6})
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:630 +0x111
github.com/pingcap/tiflow/pkg/sink/codec/avro.(*BatchEncoder).avroEncode(0xc0024faa40, {0x4859e68, 0xc0005dbe50}, 0xc0009b1760, {0xc00054957c, 0xd}, 0xff?)
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:279 +0x390
github.com/pingcap/tiflow/pkg/sink/codec/avro.(*BatchEncoder).AppendRowChangedEvent(0xc0024faa40, {0x4859e68, 0xc0005dbe50}, {0xc00054957c, 0xd}, 0xc0009b1760, 0xc0190bbe60)
        github.com/pingcap/tiflow/pkg/sink/codec/avro/avro.go:113 +0x1d8
github.com/pingcap/tiflow/pkg/sink/codec.(*encoderGroup).runEncoder(0xc003857200, {0x4859e68, 0xc0005dbe50}, 0x4)
        github.com/pingcap/tiflow/pkg/sink/codec/encoder_group.go:116 +0x385
github.com/pingcap/tiflow/pkg/sink/codec.(*encoderGroup).Run.func2()
        github.com/pingcap/tiflow/pkg/sink/codec/encoder_group.go:95 +0x2c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment]
this is the same #8958, so close this
