### ISSUE TITLE
cdc panic after updating changefeed and enabling row checksum

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9008]
### What did you do?

1. There is a kafka changefeed (avro) protocal for 4k tables running
2. enable row checksum 
```
[root@tc-ticdc-0 /]# /cdc cli changefeed --server http://127.0.0.1:8301 update -c 4k-table --sink-uri="kafka://downstream-kafka.cdc-kafka-big-cluster-tps-1712340-1-428:9092/4k-tables?protocol=avro&partition-num=3&replication-factor=3&enable-tidb-extension=true&avro-decimal-handling-mode=string&avro-bigint-unsigned-handling-mode=string" --config /tmp/changefeed2.toml
Diff of changefeed config:
{Type:update Path:[SinkURI] From:kafka://downstream-kafka.cdc-kafka-big-cluster-tps-1712340-1-428:9092/4k-tables?protocol=avro&partition-num=3&replication-factor=3 To:kafka://downstream-kafka.cdc-kafka-big-cluster-tps-1712340-1-428:9092/4k-tables?protocol=avro&partition-num=3&replication-factor=3&enable-tidb-extension=true&avro-decimal-handling-mode=string&avro-bigint-unsigned-handling-mode=string}
{Type:update Path:[Config Integrity IntegrityCheckLevel] From:none To:correctness}
Could you agree to apply changes above to changefeed [Y/N]
y
Update changefeed config successfully!
ID: 4k-table
Info: {"upstream_id":7234390566115419974,"namespace":"default","id":"4k-table","sink_uri":"kafka://downstream-kafka.cdc-kafka-big-cluster-tps-1712340-1-428:9092/4k-tables?protocol=avro\u0026partition-num=3\u0026replication-factor=3\u0026enable-tidb-extension=true\u0026avro-decimal-handling-mode=string\u0026avro-bigint-unsigned-handling-mode=string","create_time":"2023-05-19T09:35:04.998625017+08:00","start_ts":441571109431410739,"admin_job_type":1,"config":{"memory_quota":17179869184,"case_sensitive":true,"enable_old_value":true,"force_replicate":false,"ignore_ineligible_table":false,"check_gc_safe_point":true,"enable_sync_point":false,"bdr_mode":false,"sync_point_interval":600000000000,"sync_point_retention":86400000000000,"filter":{"rules":["betting_0.*"],"event_filters":null},"mounter":{"worker_num":16},"sink":{"protocol":"avro","schema_registry":"http://10.200.23.41:8081","csv":{"delimiter":",","quote":"\"","null":"\\N","include_commit_ts":false},"dispatchers":[{"matcher":["*.*"],"partition":"","topic":"tidb_{schema}_{table}"}],"column_selectors":null,"transaction_atomicity":"","encoder_concurrency":16,"terminator":"\r\n","date_separator":"none","enable_partition_separator":true,"file_index_digit":0,"enable_kafka_sink_v2":false,"only_output_updated_columns":null},"consistent":{"level":"none","max_log_size":64,"flush_interval":2000,"storage":"","use_file_backend":false},"scheduler":{"enable_table_across_nodes":true,"region_threshold":50000,"write_key_threshold":0},"integrity":{"integrity_check_level":"correctness","corruption_handle_level":"warn"}},"state":"stopped","creator_version":"v7.1.0","resolved_ts":441577519612690447,"checkpoint_ts":441577519612690447,"checkpoint_time":"2023-05-19 16:22:36.628"}
```

### What did you expect to see?

cdc should not panic

### What did you see instead?

cdc panic

```
[root@bogon bigCluster]# kubectl --kubeconfig kubeconfig.yml -n cdc-kafka-big-cluster-tps-1712340-1-428 logs -p tc-ticdc-0
[WARN] TiCDC server data-dir is not set. Please use `cdc server --data-dir` to start the cdc server if possible.
panic: send on closed channel

goroutine 1368 [running]:
github.com/pingcap/tiflow/cdc/sink/dmlsink/mq.(*dmlSink).WriteEvents(0xc019fc2280, {0xc0a5aa9880, 0x38, 0xa26?})
        github.com/pingcap/tiflow/cdc/sink/dmlsink/mq/mq_dml_sink.go:135 +0x1d1
github.com/pingcap/tiflow/cdc/sink/tablesink.(*EventTableSink[...]).UpdateResolvedTs(0x48a5500, {0xc0065a2ba0, 0x12?, 0x18?})
        github.com/pingcap/tiflow/cdc/sink/tablesink/table_sink_impl.go:126 +0x4dd
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*tableSinkWrapper).updateResolvedTs(0x0?, {0x620cc79adb00000?, 0xffffffffffffffff?, 0xc00fb9ba70?})
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_wrapper.go:194 +0xbc
github.com/pingcap/tiflow/cdc/processor/sinkmanager.advanceTableSink(0xc0a50b17a0, 0xc0a6fb6000?, 0x19288, 0x0?)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_advancer.go:327 +0x565
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*tableSinkAdvancer).advance(0xc00c01fe40, 0x0)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_advancer.go:98 +0x66e
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*tableSinkAdvancer).tryAdvanceAndAcquireMem(0xc00c01fe40, 0x1, 0x1)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_advancer.go:180 +0x410
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*tableSinkAdvancer).finish(...)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_advancer.go:255
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTask(0xc0109c2200, {0x4882e88, 0xc00fbf48c0}, 0xc0a50b17a0)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:210 +0x999
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTasks(0x0?, {0x4882e88, 0xc00fbf48c0}, 0xc0109be060)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:106 +0xc5
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startSinkWorkers.func1()
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:328 +0x33
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
panic: send on closed channel
```

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
[root@tc-ticdc-0 /]# /cdc version
Release Version: v7.1.0
Git Commit Hash: 265dddef14dfd72209a7cb55201164a0de088381
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-18 02:31:38
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false
[root@tc-ticdc-0 /]#
```

**Comment by fubinzh** [comment]
issue still seen with latest 7.1.0 build:
[root@tc-ticdc-2 /]# /cdc version
Release Version: v7.1.0
Git Commit Hash: 29afa87f9af5d388657e0afa303463a6978153f1
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-19 07:33:51
Go Version: go version go1.20.3 linux/amd64
Failpoint Build: false
