### ISSUE TITLE
DM worker panic when sync some tables 

### ISSUE THREAD

**Issue by lance6716** [pingcap/tiflow#9834]
### What did you do?

```
panic: runtime error: comparing uncomparable type []uint8

goroutine 1734018212 [running]:
github.com/pingcap/tiflow/pkg/sqlmodel.(*RowChange).IsIdentityUpdated(0x2?)
        github.com/pingcap/tiflow/pkg/sqlmodel/reduce.go:106 +0x108
github.com/pingcap/tiflow/dm/syncer.genDMLsWithSameOp({0x4003862a80, 0x106, 0x267ad60?})
        github.com/pingcap/tiflow/dm/syncer/dml.go:466 +0x134
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).genSQLs(0x400ffb8150?, {0x4003862a80?, 0x3?, 0x3?})
        github.com/pingcap/tiflow/dm/syncer/dml_worker.go:285 +0x8c
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeBatchJobs(0x4002790780, 0x9, {0x4003862a80?, 0x106, 0x12c})
        github.com/pingcap/tiflow/dm/syncer/dml_worker.go:239 +0x110
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeJobs(0x4002790780, 0x9, 0x40620fd0e0)
        github.com/pingcap/tiflow/dm/syncer/dml_worker.go:184 +0x2c0
created by github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).run
        github.com/pingcap/tiflow/dm/syncer/dml_worker.go:107 +0x5c
```

Here we may compare `[]byte`, should use bytes.Compare for this type.

https://github.com/pingcap/tiflow/blob/5d6aaa216ef8b8fc36eb2ec91680dc59b923d9c5/pkg/sqlmodel/reduce.go#L105

**Comment by lance6716** [comment]
by checking the panic stack, this problem can be workaround by setting `multiple-rows` to false

**Comment by fubinzh** [comment]
multiple-rows is false by default.

/severity moderate

**Comment by mengxian-li** [comment]
This is still present on `master`, and the blast radius grew considerably with #12541.

`IsPrimaryOrUniqueKeyUpdated`, added to `pkg/sqlmodel/reduce.go` by #12351 / #12541 ("remove redundant DELETE and force non-cascade REPLACE in safe mode"), repeats the same `pre[i] != post[i]` pattern in a new closure. On current `master` there are two occurrences, `reduce.go:91` in `IsIdentityUpdated` and `reduce.go:111` in `IsPrimaryOrUniqueKeyUpdated`.

The difference matters. The original report's stack goes through `genDMLsWithSameOp`, and the workaround suggested here was `multiple-rows: false`, which is the default. The new call site in `DMLWorker.genSQLs` has no equivalent gate:

```go
case sqlmodel.RowChangeUpdate:
    if j.safeMode {
        if j.dml.IsPrimaryOrUniqueKeyUpdated() {   // no gate
```

So on a release carrying #12541, any safe-mode UPDATE on an affected table panics deterministically. We hit this in production: workers entered `CrashLoopBackOff` and could not recover, because safe mode was enabled by config for the task rather than as a transient window after start, so there is no self-healing.

### Which columns trigger it

It is narrower than "binary columns", which may be why test coverage has missed it. Two kinds reach `sqlmodel` as `[]byte`:

| DDL | parser type | `isBinary` at `dm/syncer/dml.go:99` | value compared |
|---|---|---|---|
| `BINARY(n)`, binary `CHAR` | 254 `TypeString` | true → converted to `[]byte` | `[]byte` → panics |
| `BLOB`, `TEXT` | 252 | n/a — binlog decoder returns `[]byte` | `[]byte` → panics |
| `VARBINARY(n)` | 15 `TypeVarchar` | false | `string` → safe |
| `VARCHAR(n)` | 15 `TypeVarchar` | false | `string` → safe |

`adjustValues` converts a value to `[]byte` only when the column is `TypeString` **and** carries the binary flag, so `VARBINARY` parses to `TypeVarchar` and stays a `string`. GBK columns take the same conversion a few lines below, so they behave like the first row.

A single `BINARY(16)` primary key therefore faults on the very first comparison. That is the shape we saw.

### Why CI did not catch it

`TestIdentityUpdatedWithUniqueKeys`, added by #12541, uses `INT` keys only. The integration test `dm/tests/safe_mode_foreign_key` uses `INT` primary keys with a `VARCHAR` unique key, and `VARCHAR` compares fine. No existing case puts a `TypeString`-with-binary-flag or `BLOB` column in a key.

### Fix we are running

A byte-aware compare shared by both functions, which also removes the duplicated closure so they cannot drift apart again:

```go
func colValEqual(a, b interface{}) bool {
	aBytes, aOK := a.([]byte)
	bBytes, bOK := b.([]byte)
	if aOK || bOK {
		return aOK && bOK && bytes.Equal(aBytes, bBytes)
	}
	return reflect.DeepEqual(a, b)
}
```

`reflect.DeepEqual` in the fallback keeps any other uncomparable type from panicking here. Values with equal contents but distinct backing arrays must compare equal, otherwise a safe-mode UPDATE reports a spurious key change and writes a needless DELETE.

We have this on an internal 8.5 branch with unit tests covering a single `BINARY(16)` primary key, a multi-column primary key with trailing `BINARY` columns, and a secondary nullable `UNIQUE` index over a `BLOB` prefix. Happy to open a PR against `master` and `release-8.5` if that is useful.

**Comment by GMHDBJD** [comment]
Another production occurrence confirms that `multiple-rows: false` is no longer a sufficient workaround after the `IsPrimaryOrUniqueKeyUpdated` call was added to the single-row safe-mode path.

Environment:

- DM: `v26.3.0`, git hash `8d7a4c46e793bba86c824a539a9b1a3a472e9e2c`
- Upstream: MariaDB 10.11
- Downstream: TiDB 8.5 Serverless
- Task config: `compact: false`, `multiple-rows: false`, `safe-mode: false`, initialization `safe-mode-duration: 1m`

The worker repeatedly panicked during the automatic initialization safe-mode window:

```text
panic: runtime error: comparing uncomparable type []uint8

github.com/pingcap/tiflow/pkg/sqlmodel.(*RowChange).IsPrimaryOrUniqueKeyUpdated.func1
    github.com/pingcap/tiflow/pkg/sqlmodel/reduce.go:115
github.com/pingcap/tiflow/pkg/sqlmodel.(*RowChange).IsPrimaryOrUniqueKeyUpdated
    github.com/pingcap/tiflow/pkg/sqlmodel/reduce.go:138
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).genSQLs
    github.com/pingcap/tiflow/dm/syncer/dml_worker.go:413
github.com/pingcap/tiflow/dm/syncer.(*DMLWorker).executeBatchJobs
    github.com/pingcap/tiflow/dm/syncer/dml_worker.go:308
```

It entered `CrashLoopBackOff` and reproduced about every five minutes. We observed 279 identical panics in a 24-hour window. Each restart re-enabled initialization safe mode and replayed the same UPDATE before safe mode could expire.

As an emergency mitigation, changing the syncer config to `safe-mode-duration: 0s` restored the task. This bypass has replay/idempotency risk and is not a durable fix.

This incident confirms both comparison sites should share a byte-aware/non-comparable-safe equality helper. A regression test should cover a safe-mode UPDATE in single-row mode with `compact=false`, `multiple-rows=false`, and a `[]byte` value, in addition to the existing multiple-row scenario.
