### ISSUE TITLE
CDC panic: fetch events from an non-existent table

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9849]
### What did you do?

Create kafka changefeed and run workload

### What did you expect to see?

no panic

### What did you see instead?

```
kubectl --kubeconfig kubeconfig.yml -n stable-testbed-47l4r logs -p maincluster-ticdc-1
[WARN] TiCDC server data-dir is not set. Please use `cdc server --data-dir` to start the cdc server if possible.
panic: fetch events from an non-existent table

goroutine 1323 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x3?, 0x3?, {0x0?, 0x0?, 0xc01bc043e0?})
        go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc020e46340, {0xc01a3ff740, 0x3, 0x3})
        go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc010c71c00?, {0x4af71ed?, 0x0?}, {0xc01a3ff740, 0x3, 0x3})
        go.uber.org/zap@v1.25.0/logger.go:258 +0x51
github.com/pingcap/log.Panic({0x4af71ed?, 0xc0069649c0?}, {0xc01a3ff740?, 0x64c3?, 0x62bb?})
        github.com/pingcap/log@v1.1.1-0.20230317032135-a0d097d16e22/global.go:54 +0x85
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).FetchByTable(0xc002daca50, {0x12c74, {0xc019d49d28, 0x12, 0x18}, {0xc019d49d40, 0x12, 0x18}}, {0x62c554ef870002f, 0x62c554ef870002f}, ...)
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:193 +0x4b9
github.com/pingcap/tiflow/cdc/processor/sourcemanager.(*SourceManager).FetchByTable(0xc0024e6000, {0x12c74, {0xc019d49d28, 0x12, 0x18}, {0xc019d49d40, 0x12, 0x18}}, {0x62c554ef870002f, 0x62c554ef870002f}, ...)
        github.com/pingcap/tiflow/cdc/processor/sourcemanager/manager.go:169 +0xb0
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTask(0xc0069c2680, {0x55aa428, 0xc000e40280}, 0xc020aa6d20)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:214 +0x568
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTasks(0x24?, {0x55aa428, 0xc000e40280}, 0xc002a71080)
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:104 +0xbd
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startSinkWorkers.func1()
        github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:400 +0x2a
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1318
        golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96

```

### Versions of the cluster

[root@maincluster-ticdc-0 /]# /cdc version
Release Version: v7.4.0
Git Commit Hash: 744211d931db53bdce429063a64f4db8bf4ad3bf
Git Branch: heads/refs/tags/v7.4.0
UTC Build Time: 2023-10-09 11:58:23
Go Version: go version go1.21.1 linux/amd64
Failpoint Build: false

**Comment by hicqu** [comment]
There is a stale lock:
```
[2023/10/10 14:23:59.157 +08:00] [INFO] [endpoint.rs:575] ["the max gap of leader resolved-ts is large"] [last_resolve_attempt="{ success=false, ts=444834450364432464, reason=lock, key=Some(748000000000012FD25F72AA41139535837001) }"] [duration_to_last_update_safe_ts=1499ms] [min_memory_lock="Some((TimeStamp(444837144575607148), 74800000000000DFFF6C5F728000000000FF4C945C0000000000FA))"] [txn_num=1] [lock_num=1] [min_lock="Some((TimeStamp(444834450364432464), TxnLocks { lock_count: 1, sample_lock: Some(748000000000012FD25F72AA41139535837001) }))"] [applied_index=359] [read_state="ReadState { idx: 332, ts: 444834472240349689 }"] [gap=10194214ms] [region_id=4484803]
```

```
region_id: 4484803

lock-key: 748000000000012FD25F72AA41139535837001

region-start-key: 748000000000012FFFD25F72AA3F4422AAFF0C48860000000000FA
region-end-key : 748000000000012FFFD25F72AA60375F7CFF3B3DFA0000000000FA
```

However, TiCDC keeps trying to resolve the lock:
```
[2023/10/10 14:41:16.576 +08:00] [WARN] [region_worker.go:330] ["region not receiving resolved event from tikv or resolved ts is not pushing for too long time, try to resolve lock"] [namespace=default] [changefeed=claim-check-3] [addr=maincluster-tikv-16.maincluster-tikv-peer.stable-testbed-47l4r.svc:20160] [regionID=4484803] [span={table_id:0,start_key:748000000000012fffd25f72aa3f4422aaff0c48860000000000fa,end_key:748000000000012fffd25f72aa60375f7cff3b3dfa0000000000fa}] [duration=3h7m9.355895855s] [lastEvent=6.325962ms] [resolvedTs=444834472843280480]
[2023/10/10 14:41:16.585 +08:00] [INFO] [lock_resolver.go:131] ["resolve lock successfully"] [regionID=4484803] [lockCount=1] [maxVersion=444837413929877504] [namespace=default] [changefeed=claim-check-3]
```

**Comment by hicqu** [comment]
tikv-ctl scan --show-cf lock for the region shows:

```
key: zt\200\000\000\000\000\001/\377\322_r\252A\023\2255\377\203p\001\000\000\000\000\000\372
        lock cf value: start_ts: 444834450364432464 primary: 748000000000012FD25F728E06564E11B56DDD
```
